import { Router } from "express";
import { getHealth } from "../controllers/healthController.js";
import { getMetrics } from "../controllers/metricsController.js";
import { authenticate } from "../middleware/auth.js";
import authRoutes from "./auth.js";
import projectRoutes from "./projects.js";
import locationRoutes from "./locations.js";
import reportRoutes from "./reports.js";
import { financialRouter, projectFinancialRouter } from "./financials.js";
import anomalyRoutes from "./anomalies.js";
import riskRoutes from "./risk.js";
import analyticsRoutes from "./analytics.js";
import adminRoutes from "./admin.js";
import aiRoutes from "./ai.js";
import notificationRoutes from "./notifications.js";
import documentRoutes from "./documents.js";
import adminSeedRoutes from "./adminSeed.js";
import mpRoutes from "./mps.js";
import vendorRoutes from "./vendors.js";
import mpaAnalyticsRoutes from "./mpaAnalytics.js";
import geocodingRoutes from "./geocoding.js";
import satelliteRoutes from "./satellite.js";
import satelliteAiRoutes from "./satelliteAi.js";
import assetRoutes from "./assets.js";
import developmentRequestRoutes from "./developmentRequests.js";
import inspectionRoutes from "./inspections.js";
import caseRoutes from "./cases.js";
import contractorRoutes from "./contractors.js";
import whistleblowerRoutes from "./whistleblower.js";
import dataSourceRoutes from "./dataSources.js";
import guidelineRoutes from "./guidelines.js";
import priorityRoutes from "./priority.js";
import dataQualityRoutes from "./dataQuality.js";
import lawEnforcementRoutes from "./lawEnforcement.js";

const router = Router();

router.get("/health", getHealth);
router.get("/metrics", authenticate, getMetrics);
router.use("/auth", authRoutes);
router.use("/projects", projectRoutes);
router.use("/projects/:projectId/expenditures", projectFinancialRouter);
router.use("/projects/:projectId/documents", documentRoutes);
router.use("/locations", locationRoutes);
router.use("/reports", reportRoutes);
router.use("/financials", financialRouter);
router.use("/anomalies", anomalyRoutes);
router.use("/risk", riskRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/admin", adminRoutes);
router.use("/internal", adminSeedRoutes);
router.use("/ai", aiRoutes);
router.use("/notifications", notificationRoutes);
router.use("/documents", documentRoutes);
router.use("/mps", mpRoutes);
router.use("/vendors", vendorRoutes);
router.use("/analytics", mpaAnalyticsRoutes);
router.use("/geocoding", geocodingRoutes);
router.use("/satellite", satelliteRoutes);
router.use("/satellite", satelliteAiRoutes);
// Phase 16+: New feature routes
router.use("/assets", assetRoutes);
router.use("/development-requests", developmentRequestRoutes);
router.use("/inspections", inspectionRoutes);
router.use("/cases", caseRoutes);
router.use("/contractors", contractorRoutes);
router.use("/whistleblower", whistleblowerRoutes);
router.use("/data-sources", dataSourceRoutes);
router.use("/guidelines", guidelineRoutes);
router.use("/priority", priorityRoutes);
router.use("/data-quality", dataQualityRoutes);
router.use("/law-enforcement", lawEnforcementRoutes);

export default router;
