#!/usr/bin/env python3
import json, os

with open('src/i18n/locales/en.json','r',encoding='utf-8') as f:
    en = json.load(f)

# Sindhi translations (Arabic script, RTL)
sd = {
    'common': {
        'appName': 'ووجس', 'tagline': 'ايم پي ايل اے ڊي جوابداري پليٽ فارم',
        'loading': 'لوڊ ٿي رهي آهي...', 'error': 'نقص', 'success': 'ڪامياب',
        'save': 'سانڍيو', 'cancel': 'رد ڪيو', 'delete': 'ڊاهيو', 'edit': 'ترميم',
        'create': 'ٺاهيو', 'search': 'ڳولهاڻيو', 'filter': 'فلٽر', 'clear': 'صاف ڪريو',
        'apply': 'لاڳو ڪريو', 'back': 'واپس', 'next': 'اڳيون', 'previous': 'پوئين',
        'submit': 'جمع ڪرايو', 'reset': 'ٻيهر ترتيب ڏيو', 'confirm': 'تصديق ڪريو',
        'close': 'بند ڪريو', 'view': 'ڏسو', 'download': 'ڊائونلوڊ',
        'upload': 'اپلوڊ', 'refresh': 'ٻيهر لوڊ', 'retry': 'ٻيهر ڪوشش',
        'noData': 'ڪو به ڊيٽا ناهي', 'notFound': 'نه مليو',
        'unauthorized': 'غير مجاز', 'forbidden': 'رسائي ممناوع',
        'serverError': 'سرور جي غلطي', 'networkError': 'نيٽ ورڪ جي غلطي',
        'unknownError': 'ناڪوفي غلطي', 'pageNotFound': 'صفحو نه مليو',
        'goHome': 'ڊيش بورڊ تي وڃو', 'language': 'ٻولي', 'selectLanguage': 'ٻولي چونڊيو',
        'changeLanguage': 'ٻولي تبديل ڪريو', 'allLanguages': 'سڀ ٻوليون',
        'perPage': 'في صفحو', 'date': 'تاريخ', 'status': 'حالت', 'actions': 'عمل',
        'viewAll': 'سڀ ڏسو', 'required': 'گهربل', 'optional': 'اختياري',
        'yes': 'ها', 'no': 'نه', 'all': 'سڀ', 'select': 'چونڊيو',
        'selectOption': 'هڪ آپشن چونڊيو', 'noResults': 'ڪو به نتيجو نه مليو',
        'processing': 'پروسيس ٿي رهي آهي...', 'pending': 'زير غور',
        'active': 'فعال', 'inactive': 'غير فعال', 'completed': 'مڪمل',
        'verified': 'تصديق ٿيل', 'rejected': 'رد ٿيل', 'approved': 'منظور ٿيل',
        'inProgress': 'جاري', 'critical': 'نازڪ', 'high': 'عالي', 'medium': 'درمياني',
        'low': 'گهٽ', 'warning': 'انتباہ', 'danger': 'خطرو',
        'primary': 'بنڌي', 'secondary': 'ثانوي', 'login': 'لاگ ان',
        'logout': 'لاگ آئوٽ', 'register': 'رجسٽر', 'email': 'اي ميل',
        'password': 'پاسورڊ', 'name': 'نالو', 'description': 'وضاحت',
        'details': 'تفصيلون', 'type': 'قسم', 'amount': 'رقم', 'count': 'تعداد',
        'value': 'قدر', 'title': 'عنوان', 'notes': 'نوٽ', 'comment': 'تبصرو',
        'comments': 'تبصرو', 'message': 'پيغام', 'subject': 'موضوع', 'reason': 'سبب',
        'createdAt': 'ٺاهيو ويو', 'updatedAt': 'اپڊيٽ ٿيو', 'lastUpdated': 'آخري اپڊيٽ',
        'ago': 'اڳ', 'today': 'اڄ', 'yesterday': 'ڪل', 'thisWeek': 'هن هفتي',
        'thisMonth': 'هن مهيني', 'lastMonth': 'پوئين مهينو', 'lastWeek': 'پوئين هفتو',
        'custom': 'حسب ضرورت', 'dateRange': 'تاريخ جو رينج',
        'startDate': 'شروع جي تاريخ', 'endDate': 'ختم جي تاريخ',
        'created': 'ٺاهيو ويو', 'updated': 'اپڊيٽ ٿيو', 'deleted': 'ڊاهيو ويو',
        'by': 'طرفان', 'and': '۽', 'or': 'يا', 'more': 'وڌيڪ', 'less': 'گهٽ',
        'open': 'کوليو', 'export': 'برآمد', 'import': 'درآمد', 'print': 'پرنٽ',
        'copy': 'ڪاپي', 'copied': 'ڪاپي ٿي ويو!', 'share': 'شئير',
        'compare': 'موازنہ', 'difference': ' فرق', 'summary': 'خلاصو',
        'overview': 'جائزو', 'statistics': 'اعداد شمار', 'analytics': 'تجزيو',
        'report': 'رپورٽ', 'reports': 'رپورٽون', 'document': 'دستاويز',
        'documents': 'دستاويزون', 'file': 'فائل', 'files': 'فائلون',
        'attachment': 'منسلڪ', 'version': 'نسخو', 'history': 'تاريخ',
        'timeline': 'ٽائم لائن', 'recent': 'recent', 'top': 'سرفھرست',
        'newest': 'نئون', 'best': 'بھترين', 'worst': 'بدترين',
        'savedSuccessfully': 'ڪاميابي سان سھيو ويو',
        'deletedSuccessfully': 'ڪاميابي سان ڊاهيو ويو',
        'updatedSuccessfully': 'ڪاميابي سان اپڊيٽ ٿيو',
        'createdSuccessfully': 'ڪاميابي سان ٺاهيو ويو',
        'operationFailed': 'ڪارروائي ناڪام',
        'confirmDelete': 'ڇا توهان واقعا ڊاهڻ چاهيو ٿا؟',
        'cannotBeUndone': 'هي عمل واپس نه ٿو هلندو.',
    },
    'nav': {
        'dashboard': 'ڊيش بورڊ', 'projects': 'پروجيڪٽ', 'map': 'نقشو',
        'risk': 'خطرو', 'anomalies': 'انomalyون', 'mps': 'ممبرن',
        'vendors': 'وينڊر', 'reports': 'رپورٽون', 'notifications': 'اطلاعات',
        'citizens': 'cityizen', 'assets': 'اثاثا', 'requests': 'درخواستون',
        'inspections': 'معائنے', 'cases': 'ڪيسز', 'priority': 'ترجيح',
        'contractor': 'ٽڪيڊار', 'whistleblower': 'whistleblower',
        'dataSources': 'ڊيٽا ذريعن', 'guidelines': 'رهنما اصول',
        'analytics': 'تجزيو', 'settings': 'سيٽنگون', 'profile': 'پروفائل',
        'logout': 'لاگ آئوٽ', 'home': 'گهر', 'search': 'ڳولهاڻيو',
        'newProject': 'نئون پروجيڪٽ', 'allProjects': 'سڀ پروجيڪٽ', 'allMPs': 'سڀ ممبرن',
    },
    'auth': {
        'signIn': 'سائن ان', 'signOut': 'سائن آئوٽ', 'signUp': 'سائن اپ',
        'welcomeBack': 'واپس خوش آمد',
        'enterCredentials': 'پنهنجو اڪائونٽ تائين رسائي لاءِ اي ميل ۽ پاسورڊ درج ڪريو',
        'emailPlaceholder': 'پنهنجو اي ميل درج ڪريو',
        'passwordPlaceholder': 'پنهنجو پاسورڊ درج ڪريو',
        'rememberMe': 'مان کي ياد رکو', 'forgotPassword': 'پاسورڊ وسارايو؟',
        'loginButton': 'سائن ان', 'registerButton': 'اڪائونٽ ٺاهيو',
        'invalidCredentials': 'غلط اي ميل يا پاسورڊ',
        'createYourAccount': 'پنهنجو اڪائونٽ ٺاهيو',
        'alreadyHaveAccount': 'اڳ ئي اڪائونٽ آهي؟', 'dontHaveAccount': 'اڪائونٽ نه آهي؟',
        'selectLanguageFirst': 'پهريان پنهنجي ٻولي چونڊيو',
        'role': 'ردار', 'admin': 'ايڊمن', 'officer': 'افسر',
        'reviewer': 'جائزهڪار', 'analyst': 'تجزيهڪار',
        'viewer': 'ڏسڻوارو', 'mp': 'ممبر پارليمنٽ',
    },
    'dashboard': {
        'title': 'ڊيش بورڊ', 'subtitle': 'ايم پي ايل اے ڊي جوابداري جو جائزو',
        'totalProjects': 'ڪل پروجيڪٽ', 'activeProjects': 'فعال پروجيڪٽ',
        'completedProjects': 'مڪمل پروجيڪٽ', 'totalMPS': 'ڪل ممبرن',
        'activeMPS': 'فعال ممبرن', 'totalExpenditure': 'ڪل خرچ',
        'totalApproved': 'ڪل منظور', 'utilizationRate': 'استعمال جي شرح',
        'anomaliesDetected': 'انomalyون مليون', 'criticalAnomalies': 'نازڪ انomalyون',
        'pendingReports': 'زير غور رپورٽون', 'recentActivity': 'recent سرگرمي',
        'topPerformers': 'سڀ کان وڌيڪ ڪارڪرد', 'projectsByStatus': 'حالت موجب پروجيڪٽ',
        'projectsBySector': 'سيڪٽر موجب پروجيڪٽ', 'projectsByState': 'صوبو موجب پروجيڪٽ',
        'expenditureTrend': 'خرچ جو رجحان', 'projectProgress': 'پروجيڪٽ جي ترقي',
        'budgetUtilization': 'بجٽ استعمال', 'quickStats': 'جلد اعداد شمار',
        'recentProjects': 'recent پروجيڪٽ', 'recentAnomalies': 'recent انomalyون',
        'recentReports': 'recent رپورٽون', 'lastUpdated': 'آخري اپڊيٽ',
    },
    'projects': {
        'title': 'پروجيڪٽ', 'subtitle': 'ايم پي ايل اے ڊي ترقياتي پروجيڪٽ',
        'newProject': 'نئون پروجيڪٽ', 'searchPlaceholder': 'نالو يا آئي ڊي سميت ڳولهاڻيو...',
        'noProjectsFound': 'ڪو به پروجيڪٽ نه مليو',
        'noProjectsYet': 'هن وقت ڪو به پروجيڪٽ ناهي',
        'addFirstProject': 'شروع ڪرڻ لاءِ پهريون پروجيڪٽ شامل ڪريو',
        'projectName': 'پروجيڪٽ جو نالو', 'projectID': 'پروجيڪٽ آئي ڊي',
        'projectDetails': 'پروجيڪٽ جي تفصيلون', 'projectInformation': 'پروجيڪٽ جي معلومات',
        'projectStatus': 'پروجيڪٽ جي حالت', 'projectSector': 'سيڪٽر',
        'projectBudget': 'بجٽ', 'projectLocation': 'مقام', 'projectTimeline': 'ٽائم لائن',
        'projectProgress': 'ترقي', 'projectContractor': 'ٽڪيڊار',
        'projectDescription': 'وضاحت', 'projectStartDate': 'شروع جي تاريخ',
        'projectEndDate': 'ختم جي تاريخ', 'projectCost': 'لاگت',
        'approvedAmount': 'منظور ٿيل رقم', 'spentAmount': 'خرچ ٿيل رقم',
        'remainingAmount': 'باقي رقم', 'utilization': 'استعمال',
        'utilizationRate': 'استعمال جي شرح', 'utilizationPercent': '{{value}}% استعمال',
        'utilizationOfApproved': 'منظور بجٽ جو استعمال',
        'overBudget': 'بجٽ کان وڌيڪ', 'underBudget': 'بجٽ کان گهٽ',
        'onTrack': 'وقت تي', 'behindSchedule': 'شيديول کان پوئين',
        'delayed': 'موڪليل', 'onTime': 'وقت تي', 'district': 'ضلعو',
        'state': 'صوبو', 'constituency': 'ڪنسٽيچوئنسي',
        'allDistricts': 'سڀ ضلعا', 'allStates': 'سڀ صوبا', 'allSectors': 'سڀ سيڪٽر',
        'allStatuses': 'سڀ حالتون', 'filterByDistrict': 'ضلع موجب فلٽر',
        'filterByState': 'صوبو موجب فلٽر', 'filterBySector': 'سيڪٽر موجب فلٽر',
        'sortByName': 'نالو موجب ترتيب', 'sortByDate': 'تاريخ موجب ترتيب',
        'sortByBudget': 'بجٽ موجب ترتيب', 'projectList': 'پروجيڪٽ فهرست',
        'projectCount': '{{count}} پروجيڪٽ', 'relatedProjects': 'لاڳاپيل پروجيڪٽ',
        'viewProject': 'پروجيڪٽ ڏسو', 'editProject': 'پروجيڪٽ ترميم ڪريو',
        'deleteProject': 'پروجيڪٽ ڊاهيو', 'projectDeleted': 'پروجيڪٽ ڪاميابي سان ڊاهيو ويو',
        'projectCreated': 'پروجيڪٽ ڪاميابي سان ٺاهيو ويو',
        'projectUpdated': 'پروجيڪٽ ڪاميابي سان اپڊيٽ ٿيو',
        'addLocation': 'مقام شامل ڪريو', 'addExpenditure': 'خرچ شامل ڪريو',
        'addDocument': 'دستاويز شامل ڪريو', 'viewTimeline': 'ٽائم لائن ڏسو',
        'viewOnMap': 'نقشي تي ڏسو', 'viewSatellite': 'سيٽلائيٽ ڏسو',
        'viewDocuments': 'دستاويزون ڏسو', 'worksBreakdown': 'ڪمن جي تفصيل',
        'expenditureRecords': 'خرچ جا رڪارڊ', 'expenditureDetails': 'خرچ جي تفصيلون',
        'financialSummary': 'ماليات جو خلاصو', 'financialRecords': 'ماليات جا رڪارڊ',
        'expenditureAmount': 'خرچ جي رقم', 'paymentStatus': 'ادائيگي جي حالت',
        'paid': 'ادا ٿيل', 'totalExpenditure': 'ڪل خرچ',
        'transactionCount': '{{count}} ليني ديني',
        'goToProject': 'پروجيڪٽ تي وڃو', 'viewAllProjects': 'سڀ پروجيڪٽ ڏسو',
    },
    'mps': {
        'title': 'ممبرن پارليمنٽ', 'subtitle': 'پارليمنٽري ممبرن جا رڪارڊ',
        'newMP': 'نئون ممبر',
        'searchPlaceholder': 'نالو يا ڪنسٽيچوئنسي سميت ڳولهاڻيو...',
        'noMPsFound': 'ڪو به ممبر نه مليو', 'noMPsYet': 'هن وقت ڪو به ممبر نه آهي',
        'addFirstMP': 'شروع ڪرڻ لاءِ پهريون ممبر شامل ڪريو',
        'mpName': 'ممبر جو نالو', 'mpDetails': 'ممبر جي تفصيلون',
        'mpInformation': 'ممبر جي معلومات', 'mpProfile': 'ممبر پروفائل',
        'mpConstituency': 'ڪنسٽيچوئنسي', 'mpState': 'صوبو', 'mpParty': 'پارٽي',
        'mpTerm': 'مدو', 'mpAttendance': 'حاضري', 'mpHouse': 'ايوان',
        'lokSabha': 'لوڪ سبها', 'rajyaSabha': 'راجيا سبها', 'allHouses': 'سڀ اوان',
        'allStates': 'سڀ صوبا', 'mpList': 'ممبرن جي فهرست',
        'mpCount': '{{count}} ممبرن', 'viewMP': 'ممبر ڏسو',
        'editMP': 'ممبر ترميم ڪريو', 'deleteMP': 'ممبر ڊاهيو',
        'mpDeleted': 'ممبر ڪاميابي سان ڊاهيو ويو', 'addProject': 'پروجيڪٽ شامل ڪريو',
        'viewProjects': 'پروجيڪٽ ڏسو', 'viewAllProjects': 'سڀ پروجيڪٽ ڏسو',
        'mpProjects': 'ممبر جا پروجيڪٽ', 'projectsCount': '{{count}} پروجيڪٽ',
        'projectBudget': 'پروجيڪٽ بجٽ', 'totalProjects': 'ڪل پروجيڪٽ',
        'approvedBudget': 'منظور بجٽ', 'spentBudget': 'خرچ بجٽ',
        'utilizationRate': 'استعمال جي شرح', 'utilizationPercent': '{{value}}% استعمال',
        'topSectors': 'سرفھرست سيڪٽر', 'mpOverview': 'جائزو',
        'mpSpending': 'ايم پي ايل اے ڊي خرچ', 'weeklyProgress': 'هفتوار ترقي',
        'satelliteView': 'سيٽلائيٽ', 'externalLinks': 'ٻاهرين لنڪ',
        'weeklyActivity': 'هفتوار سرگرمي', 'weeklyExpenditure': 'هفتوار خرچ',
        'weeklyCompleted': 'هفتوار مڪمل', 'weeklyStarted': 'هفتوار شروع',
        'weeklyAnomalies': 'هفتوار انomalyون', 'weeklyReports': 'هفتوار رپورٽون',
        'satelliteOverview': 'سيٽلائيٽ جائزو', 'activeConstruction': 'فعال تعمير',
        'completedSites': 'مڪمل سائيٽ', 'developmentScore': 'ترقي جو اسڪور',
        'avgDevelopmentScore': 'اوسط ترقي اسڪور', 'activeSites': 'فعال سائيٽ',
        'siteCleared': 'سائيٽ صاف', 'foundation': 'بنيا', 'structure': 'ڍانچو',
        'nearComplete': 'قریب مڪمل', 'noActivity': 'ڪو به سرگرمي ناهي',
        'mpladsEntitlement': 'ايم پي ايل اے ڊي حق',
        'mpladsReceived': 'ايم پي ايل اے ڊي وصول ٿيو',
        'mpladsExpenditure': 'ايم پي ايل اے ڊي خرچ',
        'mpladsUtilization': 'ايم پي ايل اے ڊي استعمال',
        'goToMP': 'ممبر تي وڃو', 'viewAllMPs': 'سڀ ممبرن ڏسو',
        'anomaliesDetected': 'انomalyون مليون', 'riskIndicators': 'خطري جا اشاري',
        'projectCount': 'پروجيڪٽ تعداد', 'last4Weeks': 'آخري 4 هفتا',
        'last12Weeks': 'آخري 12 هفتا', 'totalExpenditure': 'ڪل خرچ',
        'projectsStarted': 'شروع ٿيل پروجيڪٽ', 'projectsCompleted': 'مڪمل پروجيڪٽ',
        'avgWeeklyExpenditure': 'اوسط هفتوار خرچ',
    },
    'anomalies': {
        'title': 'انomalyون', 'subtitle': 'ڳولهي ويل انomalyون ۽ فلیگ',
        'newAnomaly': 'نئين انomaly', 'searchPlaceholder': 'انomalyون ڳولهاڻيو...',
        'noAnomaliesFound': 'ڪو به انomaly نه مليو',
        'noAnomaliesYet': 'هن وقت ڪو به انomaly ناهي',
        'anomalyDetails': 'انomaly جي تفصيلون', 'anomalyType': 'قسم',
        'anomalySeverity': 'Severity', 'anomalyStatus': 'حالت',
        'anomalyDescription': 'وضاحت', 'anomalyRule': 'قاعدو',
        'anomalyProject': 'پروجيڪٽ', 'anomalyDate': 'تاريخ',
        'viewAnomaly': 'انomaly ڏسو', 'resolveAnomaly': 'حل ڪريو',
        'dismissAnomaly': 'رد ڪريو', 'anomalyCount': '{{count}} انomalyون',
        'criticalCount': '{{count}} نازڪ', 'highCount': '{{count}} عالي',
        'openAnomalies': 'کليل انomalyون', 'resolvedAnomalies': 'حل ٿيل انomalyون',
        'overBudgetAnomaly': 'بجٽ کان وڌيڪ', 'delayedAnomaly': 'موڪليل پروجيڪٽ',
        'noContractorAnomaly': 'ڪو به ٽڪيڊار ناهي', 'fakeProjectAnomaly': 'ممڪنه نقل',
        'unusualExpenditureAnomaly': 'غير معمول خرچ', 'relatedProjects': 'لاڳاپيل پروجيڪٽ',
    },
    'reports': {
        'title': 'رپورٽون', 'subtitle': 'پروجيڪٽ نگراني رپورٽون',
        'newReport': 'نئين رپورٽ', 'searchPlaceholder': 'رپورٽون ڳولهاڻيو...',
        'noReportsFound': 'ڪو به رپورٽ نه مليو',
        'noReportsYet': 'هن وقت ڪو به رپورٽ ناهي',
        'reportDetails': 'رپورٽ جي تفصيلون', 'reportType': 'رپورٽ جو قسم',
        'reportStatus': 'حالت', 'reportDescription': 'وضاحت',
        'reportProject': 'پروجيڪٽ', 'reportDate': 'تاريخ',
        'reportAuthor': 'رپورٽ ڪندڙ', 'viewReport': 'رپورٽ ڏسو',
        'reportCount': '{{count}} رپورٽون', 'submittedReports': 'جمع ٿيل رپورٽون',
        'pendingReports': 'زير غور رپورٽون', 'verifiedReports': 'تصديق ٿيل رپورٽون',
        'rejectedReports': 'رد ٿيل رپورٽون', 'verifyReport': 'تصديق ڪريو',
        'rejectReport': 'رد ڪريو', 'submitReport': 'رپورٽ جمع ڪرايو',
        'recommendations': 'سفارشون',
    },
    'vendors': {
        'title': 'وينڊر', 'subtitle': 'ٽڪيڊار ۽ وينڊر',
        'newVendor': 'نئون وينڊر', 'searchPlaceholder': 'وينڊر ڳولهاڻيو...',
        'noVendorsFound': 'ڪو به وينڊر نه مليو',
        'vendorDetails': 'وينڊر جون تفصيلون', 'vendorName': 'وينڊر جو نالو',
        'vendorAddress': 'پتو', 'vendorPhone': 'فون', 'vendorEmail': 'اي ميل',
        'vendorState': 'صوبو', 'vendorDistrict': 'ضلعو',
        'vendorCount': '{{count}} وينڊر', 'projectCount': '{{count}} پروجيڪٽ',
        'viewVendor': 'وينڊر ڏسو', 'topVendors': 'سرفھرست وينڊر',
    },
    'map': {
        'title': 'نقشو', 'subtitle': 'جغرافيائي پروجيڪٽ جو نظارو',
        'loading': 'نقشو لوڊ ٿي رهي آهي...', 'noLocationData': 'مقام جو ڊيٽا ناهي',
        'zoomIn': 'زوم ان', 'zoomOut': 'زوم آئوٽ', 'fullscreen': 'مڪمل اسڪرين',
        'legend': 'ليجنڊ', 'coordinate': 'نقاط', 'latitude': 'عرض',
        'longitude': 'طول', 'addLocation': 'مقام شامل ڪريو',
    },
    'analytics': {
        'title': 'تجزيو', 'subtitle': 'ڊيٽا جا اشارو ۽ رجحان',
        'overview': 'جائزو', 'trends': 'رجحان', 'comparisons': 'موازنہ',
        'projectAnalytics': 'پروجيڪٽ تجزيو', 'mpAnalytics': 'ممبر تجزيو',
        'vendorAnalytics': 'وينڊر تجزيو', 'expenditureAnalytics': 'خرچ تجزيو',
        'riskAnalytics': 'خطرو تجزيو', 'totalBudget': 'ڪل بجٽ',
        'totalSpent': 'ڪل خرچ', 'totalApproved': 'ڪل منظور',
        'budgetAnalysis': 'بجٽ تجزيو', 'riskAnalysis': 'خطرو تجزيو',
        'topMPs': 'سرفھرست ممبرن', 'anomalyDistribution': 'انomaly تقسيم',
    },
    'satellite': {
        'title': 'سيٽلائيٽ تصوير', 'subtitle': 'سيٽلائيٽ کان تعميراتي ترقي',
        'loading': 'سيٽلائيٽ ڊيٽا لوڊ ٿي رهي آهي...',
        'noDataAvailable': 'هن پروجيڪٽ لاءِ سيٽلائيٽ ڊيٽا دستياب ناهي',
        'developmentScore': 'ترقي جو اسڪور', 'developmentCurve': 'ترقي جو خم',
        'builtUpArea': 'تعمير شده علائقو', 'vegetationCover': 'وڻڙي جو احاطو',
        'constructionConfidence': 'تعميراتي يقين', 'weeklyCaptures': 'هفتوار ڪيپچر',
        'latestCapture': 'تازو ڪيپچر', 'captureDate': 'ڪيپچر جي تاريخ',
        'viewFullTimeline': 'مڪمل ٽائم لائن ڏسو', 'analysis': 'تجزيو',
        'runAnalysis': 'تجزيو هلائيو', 'noActivity': 'ڪو به سرگرمي ناهي',
        'siteCleared': 'سائيٽ صاف', 'foundation': 'بنيا', 'structure': 'ڍانچو',
        'nearComplete': 'قریب مڪمل', 'completed': 'مڪمل',
        'addPrimaryLocation': 'پهريان ۽ بعد جون تصويرون ڏسڻ لاءِ بنڌي مقام شامل ڪريو',
    },
    'risk': {
        'title': 'خطرو تجزيو', 'subtitle': 'پروجيڪٽ جي خطري جا اشاري',
        'overallRiskScore': 'مجموعي خطرو اسڪور', 'riskLevel': 'خطري جو درجو',
        'riskFactors': 'خطري جا عنصر', 'financialRisk': 'ماليات جو خطرو',
        'scheduleRisk': 'شيديول جو خطرو', 'qualityRisk': 'معيار جو خطرو',
        'complianceRisk': 'تعميل جو خطرو', 'lowRisk': 'گهٽ خطرو',
        'mediumRisk': 'درمياني خطرو', 'highRisk': 'عالي خطرو',
        'criticalRisk': 'نازڪ خطرو', 'riskIndicators': 'خطري جا اشاري',
        'riskDashboard': 'خطرو ڊيش بورڊ', 'riskDistribution': 'خطرو تقسيم',
        'riskBySector': 'سيڪٽر موجب خطرو', 'riskByState': 'صوبو موجب خطرو',
        'riskByMP': 'ممبر موجب خطرو', 'riskTrend': 'خطرو رجحان',
        'riskOverTime': 'وقت سان خطرو',
    },
    'settings': {
        'title': 'سيٽنگون', 'subtitle': 'ايپليڪيشن جا ترجيح',
        'general': 'عام', 'account': 'اڪائونٽ', 'appearance': 'ظاهر',
        'notifications': 'اطلاعات', 'security': 'سیکیورٹي', 'language': 'ٻولي',
        'languageSettings': 'ٻولي سيٽنگون', 'selectLanguage': 'ٻولي چونڊيو',
        'languageChanged': 'ٻولي ڪاميابي سان تبديل ٿي وئي',
        'currentLanguage': 'موجوده ٻولي', 'theme': 'ٿیم',
        'lightMode': 'لائيٽ موڊ', 'darkMode': 'ڊارڪ موڊ',
        'systemDefault': 'سسٽم ڊيفالٽ', 'changePassword': 'پاسورڊ تبديل ڪريو',
        'about': 'بابت', 'version': 'نسخو',
    },
    'validation': {
        'required': 'هي فيلڊ گهربل آهي',
        'email': 'مهرباني ڪري درست اي ميل درج ڪريو',
        'password': 'پاسورڊ گهٽ ۾ گهٽ 8 اکرن جو هجڻ گهرجي',
    },
    'time': {
        'seconds': '{{count}} سيڪنڊ', 'minutes': '{{count}} منٽ',
        'hours': '{{count}} ڪلاڪ', 'days': '{{count}} ڏينهن',
        'weeks': '{{count}} هفتا', 'months': '{{count}} مهينا',
        'years': '{{count}} سال', 'justNow': 'هاڻي', 'aDay': 'هڪ ڏينهن',
    },
    'format': {
        'currency': '₹{{value}}', 'currencyCrore': '₹{{value}} ڪروڙ',
        'currencyLakh': '₹{{value}} لک', 'percentage': '{{value}}%',
    }
}

def merge(base, override):
    result = {}
    for k in set(list(base.keys()) + list(override.keys())):
        if k in base and k in override and isinstance(base[k], dict) and isinstance(override[k], dict):
            result[k] = merge(base[k], override[k])
        elif k in override:
            result[k] = override[k]
        else:
            result[k] = base.get(k, '')
    return result

merged = merge(en, sd)
with open('src/i18n/locales/sd.json','w',encoding='utf-8') as f:
    json.dump(merged, f, ensure_ascii=False, indent=2)
print(f'sd.json: {os.path.getsize("src/i18n/locales/sd.json")} bytes')
