#!/usr/bin/env python3
"""Generate all VOJAS locale files from English template.

This script copies en.json and applies translations from T (translation dict).
"""

import json
import os

LOCALE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "frontend", "src", "i18n", "locales")

# Translation dictionary - map of lang_code -> {key: translation}
# Missing keys use English values
T = {}

# Common translations for all languages
COMMON = {
    "common.appName": "VOJAS",
    "common.tagline": "MPLAD Accountability Platform",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.clear": "Clear",
    "common.apply": "Apply",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.reset": "Reset",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.view": "View",
    "common.download": "Download",
    "common.upload": "Upload",
    "common.refresh": "Refresh",
    "common.retry": "Retry",
    "common.noData": "No data available",
    "common.notFound": "Not found",
    "common.unauthorized": "Unauthorized",
    "common.forbidden": "Access denied",
    "common.serverError": "Server error",
    "common.networkError": "Network error",
    "common.unknownError": "An unknown error occurred",
    "common.pageNotFound": "Page not found",
    "common.goHome": "Go to Dashboard",
    "common.language": "Language",
    "common.selectLanguage": "Select Language",
    "common.changeLanguage": "Change Language",
    "common.allLanguages": "All Languages",
    "common.perPage": "per page",
    "common.of": "of",
    "common.showing": "Showing",
    "common.total": "Total",
    "common.from": "From",
    "common.to": "To",
    "common.date": "Date",
    "common.status": "Status",
    "common.actions": "Actions",
    "common.viewAll": "View All",
    "common.showMore": "Show More",
    "common.showLess": "Show Less",
    "common.required": "Required",
    "common.optional": "Optional",
    "common.yes": "Yes",
    "common.no": "No",
    "common.true": "True",
    "common.false": "False",
    "common.all": "All",
    "common.none": "None",
    "common.other": "Other",
    "common.select": "Select",
    "common.selectOption": "Select an option",
    "common.noResults": "No results found",
    "common.processing": "Processing...",
    "common.pending": "Pending",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.enabled": "Enabled",
    "common.disabled": "Disabled",
    "common.completed": "Completed",
    "common.verified": "Verified",
    "common.rejected": "Rejected",
    "common.approved": "Approved",
    "common.proposed": "Proposed",
    "common.inProgress": "In Progress",
    "common.cancelled": "Cancelled",
    "common.critical": "Critical",
    "common.high": "High",
    "common.medium": "Medium",
    "common.low": "Low",
    "common.info": "Info",
    "common.warning": "Warning",
    "common.danger": "Danger",
    "common.primary": "Primary",
    "common.secondary": "Secondary",
    "common.light": "Light",
    "common.dark": "Dark",
    "common.login": "Login",
    "common.logout": "Logout",
    "common.register": "Register",
    "common.email": "Email",
    "common.password": "Password",
    "common.name": "Name",
    "common.description": "Description",
    "common.details": "Details",
    "common.type": "Type",
    "common.category": "Category",
    "common.amount": "Amount",
    "common.count": "Count",
    "common.value": "Value",
    "common.label": "Label",
    "common.title": "Title",
    "common.subtitle": "Subtitle",
    "common.note": "Note",
    "common.notes": "Notes",
    "common.comment": "Comment",
    "common.comments": "Comments",
    "common.message": "Message",
    "common.subject": "Subject",
    "common.body": "Body",
    "common.reason": "Reason",
    "common.reasonForRejecting": "Reason for rejection",
    "common.noReasonProvided": "No reason provided",
    "common.createdAt": "Created",
    "common.updatedAt": "Updated",
    "common.lastUpdated": "Last updated",
    "common.addedOn": "Added on",
    "common.resolvedOn": "Resolved on",
    "common.lastSeen": "Last seen",
    "common.ago": "ago",
    "common.fromNow": "from now",
    "common.today": "Today",
    "common.yesterday": "Yesterday",
    "common.thisWeek": "This week",
    "common.thisMonth": "This month",
    "common.lastMonth": "Last month",
    "common.lastWeek": "Last week",
    "common.last7Days": "Last 7 days",
    "common.last30Days": "Last 30 days",
    "common.last90Days": "Last 90 days",
    "common.thisYear": "This year",
    "common.custom": "Custom",
    "common.dateRange": "Date Range",
    "common.startDate": "Start Date",
    "common.endDate": "End Date",
    "common.estimatedDate": "Estimated Date",
    "common.targetDate": "Target Date",
    "common.actualDate": "Actual Date",
    "common.projectedDate": "Projected Date",
    "common.completedDate": "Completed Date",
    "common.expectedDate": "Expected Date",
    "common.created": "Created",
    "common.updated": "Updated",
    "common.deleted": "Deleted",
    "common.by": "by",
    "common.of2": "of",
    "common.over": "over",
    "common.under": "under",
    "common.and": "and",
    "common.or2": "or",
    "common.more": "More",
    "common.less": "Less",
    "common.open": "Open",
    "common.close": "Close",
    "common.expanded": "Expanded",
    "common.collapsed": "Collapsed",
    "common.expand": "Expand",
    "common.collapse": "Collapse",
    "common.zoomIn": "Zoom In",
    "common.zoomOut": "Zoom Out",
    "common.resetZoom": "Reset Zoom",
    "common.fullscreen": "Fullscreen",
    "common.exitFullscreen": "Exit Fullscreen",
    "common.refreshData": "Refresh Data",
    "common.export": "Export",
    "common.import": "Import",
    "common.print": "Print",
    "common.copy": "Copy",
    "common.copied": "Copied!",
    "common.share": "Share",
    "common.compare": "Compare",
    "common.difference": "Difference",
    "common.summary": "Summary",
    "common.overview": "Overview",
    "common.statistics": "Statistics",
    "common.analytics": "Analytics",
    "common.report": "Report",
    "common.reports": "Reports",
    "common.document": "Document",
    "common.documents": "Documents",
    "common.file": "File",
    "common.files": "Files",
    "common.uploadFile": "Upload File",
    "common.downloadFile": "Download File",
    "common.attachment": "Attachment",
    "common.attachments": "Attachments",
    "common.noAttachments": "No attachments",
    "common.version": "Version",
    "common.versions": "Versions",
    "common.history": "History",
    "common.timeline": "Timeline",
    "common.recent": "Recent",
    "common.earlier": "Earlier",
    "common.upcoming": "Upcoming",
    "common.trending": "Trending",
    "common.top": "Top",
    "common.newest": "Newest",
    "common.oldest": "Oldest",
    "common.largest": "Largest",
    "common.smallest": "Smallest",
    "common.highest": "Highest",
    "common.lowest": "Lowest",
    "common.fastest": "Fastest",
    "common.slowest": "Slowest",
    "common.best": "Best",
    "common.worst": "Worst",
    "common.clearFilters": "Clear filters",
    "common.noFiltersApplied": "No filters applied",
    "common.filterApplied": "Filter applied",
    "common.resultsFiltered": "Results filtered",
    "common.dataRefreshed": "Data refreshed",
    "common.savedSuccessfully": "Saved successfully",
    "common.deletedSuccessfully": "Deleted successfully",
    "common.updatedSuccessfully": "Updated successfully",
    "common.createdSuccessfully": "Created successfully",
    "common.operationFailed": "Operation failed",
    "common.confirmDelete": "Are you sure you want to delete this?",
    "common.confirmAction": "Are you sure you want to proceed?",
    "common.cannotBeUndone": "This action cannot be undone.",
}


def apply_translations(base, translations):
    """Apply translations to base object, return new object."""
    result = json.loads(json.dumps(base))
    for key, value in translations.items():
        parts = key.split('.')
        obj = result
        for p in parts[:-1]:
            obj = obj[p]
        obj[parts[-1]] = value
    return result


def main():
    en_path = os.path.join(LOCALE_DIR, "en.json")
    with open(en_path, 'r', encoding='utf-8') as f:
        en = json.load(f)

    print(f"Loaded English template: {len(en)} namespaces")

    # Generate a file for each language that has translations
    for lang, translations in T.items():
        # Start with English
        result = apply_translations(en, translations)
        out_path = os.path.join(LOCALE_DIR, f"{lang}.json")
        with open(out_path, 'w', encoding='utf-8') as f:
            json.dump(result, f, ensure_ascii=False, indent=2)
        print(f"Generated {out_path}: {len(translations)} keys translated")

    print(f"\nDone! {len(T)} languages processed.")


if __name__ == "__main__":
    main()
