#!/usr/bin/env python3
"""Generate locale files for the 13 remaining Indian languages."""
import json, os

with open('src/i18n/locales/en.json','r',encoding='utf-8') as f:
    en = json.load(f)

def merge(base, override):
    result = {}
    for k in set(list(base.keys()) + list(override.keys())):
        if k in base and k in override and isinstance(base[k], dict) and isinstance(override[k], dict):
            result[k] = merge(base[k], override[k])
        elif k in override:
            result[k] = override[k]
        else:
            result[k] = base.get(k, '')
    return result

def write_locale(code, trans):
    merged = merge(en, trans)
    path = f'src/i18n/locales/{code}.json'
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print(f'{code}.json: {os.path.getsize(path)} bytes')

# ── Odia (or) ─────────────────────────────────────────────────────────────────
or_data = {
    'common': {
        'appName': 'ୱୋଜାସ', 'tagline': 'ଏମ.ପି.ଏଲ.ଏ.ଡି. ଉତ୍ତରଦାୟିତା ପ୍ଲାଟଫର୍ମ',
        'loading': 'ଲୋଡ୍ ହେଉଛି...', 'error': 'ତୃଟି', 'success': 'ସଫଳ',
        'save': 'ସଂରକ୍ଷଣ କରନ୍ତୁ', 'cancel': 'ବାତିଲ କରନ୍ତୁ', 'delete': 'ବିଲୋପ କରନ୍ତୁ', 'edit': 'ସଂପାଦନ କରନ୍ତୁ',
        'create': 'ନିର୍ମାଣ କରନ୍ତୁ', 'search': 'ସନ୍ଧାନ କରନ୍ତୁ', 'filter': 'ଫିଲ୍ଟର', 'clear': 'ସଫା କରନ୍ତୁ',
        'apply': 'ପ୍ରୟୋଗ କରନ୍ତୁ', 'back': 'ପଛକୁ', 'next': 'ପରବର୍ତ୍ତୀ', 'previous': 'ପୂର୍ବବର୍ତ୍ତୀ',
        'submit': 'ଦାଖଲ କରନ୍ତୁ', 'reset': 'ପୁନଃସେଟ୍', 'confirm': 'ନିଶ୍ଚିତ କରନ୍ତୁ',
        'close': 'ବନ୍ଦ କରନ୍ତୁ', 'view': 'ଦେଖନ୍ତୁ', 'download': 'ଡାଉନଲୋଡ୍',
        'upload': 'ଅପଲୋଡ୍', 'refresh': 'ତାଜା କରନ୍ତୁ', 'retry': 'ପୁନଃପ୍ରୟାସ କରନ୍ତୁ',
        'noData': 'କୌଣସି ତଥ୍ୟ ନାହିଁ', 'notFound': 'ମିଳିଲା ନାହିଁ',
        'unauthorized': 'ଅନୁମତି ନାହିଁ', 'forbidden': 'ପ୍ରବେଶ ନିଷିଧ',
        'serverError': 'ସର୍ଭର ତୃଟି', 'networkError': 'ନେଟ୍‍ୱର୍କ ତୃଟି',
        'unknownError': 'ଅଜଣା ତୃଟି', 'pageNotFound': 'ପୃଷ୍ଠା ମିଳିଲା ନାହିଁ',
        'goHome': 'ଡ୍ୟାସବୋର୍ଡକୁ ଯାଆନ୍ତୁ', 'language': 'ଭାଷା', 'selectLanguage': 'ଭାଷା ବାଛନ୍ତୁ',
        'changeLanguage': 'ଭାଷା ପରିବର୍ତ୍ତନ କରନ୍ତୁ', 'allLanguages': 'ସମସ୍ତ ଭାଷା',
        'perPage': 'ପ୍ରତି ପୃଷ୍ଠା', 'date': 'ତାରିଖ', 'status': 'ସ୍ଥିତି', 'actions': 'କାର୍ଯ୍ୟ',
        'viewAll': 'ସବୁ ଦେଖନ୍ତୁ', 'required': 'ଆବଶ୍ୟକ', 'optional': 'ବୈକଳ୍ପିକ',
        'yes': 'ହଁ', 'no': 'ନାହିଁ', 'all': 'ସମସ୍ତ', 'select': 'ବାଛନ୍ତୁ',
        'selectOption': 'ଗୋଟିଏ ବିକଳ୍ପ ବାଛନ୍ତୁ', 'noResults': 'କୌଣସି ଫଳାଫଳ ମିଳିଲା ନାହିଁ',
        'processing': 'ପ୍ରକ୍ରିୟାକରଣ ଚାଲିଛି...', 'pending': 'ବିଚାରାଧୀନ',
        'active': 'ସକ୍ରିୟ', 'inactive': 'ନିଷ୍କ୍ରିୟ', 'completed': 'ସମ୍ପୂର୍ଣ୍ଣ',
        'verified': 'ଯାଞ୍ଚିତ', 'rejected': 'ପ୍ରତ୍ୟାଖ୍ୟାତ', 'approved': 'ଅନୁମୋଦିତ',
        'inProgress': 'ଚାଲିଛି', 'critical': 'ଗମ୍ଭୀର', 'high': 'ଉଚ୍ଚ', 'medium': 'ମଧ୍ୟମ',
        'low': 'ନିମ୍ନ', 'warning': 'ଚେତାବନୀ', 'danger': 'ବିପଦ',
        'primary': 'ପ୍ରାଥମିକ', 'secondary': 'ସାପେକ୍ଷ', 'login': 'ଲଗ୍ ଇନ୍',
        'logout': 'ଲଗ୍ ଆଉଟ୍', 'register': 'ପଞ୍ଜୀକରଣ', 'email': 'ଇମେଲ୍',
        'password': 'ପାସୱାର୍ଡ', 'name': 'ନାମ', 'description': 'ବର୍ଣ୍ଣନା',
        'details': 'ବିସ୍ତୃତ', 'type': 'ପ୍ରକାର', 'amount': 'ରାଶି', 'count': 'ଗଣନା',
        'value': 'ମୂଲ୍ୟ', 'title': 'ଶୀର୍ଷକ', 'notes': 'ଟୀକା', 'comment': 'ମନ୍ତବ୍ୟ',
        'comments': 'ମନ୍ତବ୍ୟ', 'message': 'ବାର୍ତ୍ତା', 'subject': 'ବିଷୟ', 'reason': 'କାରଣ',
        'createdAt': 'ସୃଷ୍ଟି ହୋଇଛି', 'updatedAt': 'ଅଦ୍ୟତନ ହୋଇଛି', 'lastUpdated': 'ଶେଷ ଅଦ୍ୟତନ',
        'ago': 'ପୂର୍ବେ', 'today': 'ଆଜି', 'yesterday': 'ଗତକାଲି', 'thisWeek': 'ଏହି ସପ୍ତାହ',
        'thisMonth': 'ଏହି ମାସ', 'lastMonth': 'ଗତ ମାସ', 'lastWeek': 'ଗତ ସପ୍ତାହ',
        'custom': 'କଷ୍ଟମ୍', 'dateRange': 'ତାରିଖ ସୀମା',
        'startDate': 'ଆରମ୍ଭ ତାରିଖ', 'endDate': 'ଶେଷ ତାରିଖ',
        'created': 'ସୃଷ୍ଟି', 'updated': 'ଅଦ୍ୟତନ', 'deleted': 'ବିଲୋପିତ',
        'by': 'ଦ୍ୱାରା', 'and': 'ଏବଂ', 'or': 'କିମ୍ୱା', 'more': 'ଅଧିକ', 'less': 'କମ୍',
        'open': 'ଖୋଲନ୍ତୁ', 'export': 'ରପ୍ତାନି', 'import': 'ଆମଦାନି', 'print': 'ମୁଦ୍ରଣ',
        'copy': 'କପି', 'copied': 'କପି ହୋଇଛି!', 'share': 'ସେୟାର କରନ୍ତୁ',
        'compare': 'ତୁଳନା', 'difference': 'ପାର୍ଥକ୍ୟ', 'summary': 'ସାରାଂଶ',
        'overview': 'ସମୀକ୍ଷା', 'statistics': 'ପରିସଂଖ୍ୟାନ', 'analytics': 'ବିଶ୍ଳେଷଣ',
        'report': 'ରିପୋର୍ଟ', 'reports': 'ରିପୋର୍ଟଗୁଡିକ', 'document': 'ଦସ୍ତାବେଜ',
        'documents': 'ଦସ୍ତାବେଜଗୁଡିକ', 'file': 'ଫାଇଲ', 'files': 'ଫାଇଲଗୁଡିକ',
        'attachment': 'ସଂଲଗ୍ନକ', 'version': 'ସଂସ୍କରଣ', 'history': 'ଇତିହାସ',
        'timeline': 'ସମୟରେଖା', 'recent': 'ସାମ୍ପ୭ତିକ', 'top': 'ଶୀର୍ଷ',
        'newest': 'ନୂତନ', 'best': 'ସର୍ବୋତ୍ତମ', 'worst': 'ସର୍ବାଧିକ ଖରାପ',
        'savedSuccessfully': 'ସଫଳତାର ସହିତ ସଂରକ୍ଷିତ',
        'deletedSuccessfully': 'ସଫଳତାର ସହିତ ବିଲୋପିତ',
        'updatedSuccessfully': 'ସଫଳତାର ସହିତ ଅଦ୍ୟତନ',
        'createdSuccessfully': 'ସଫଳତାର ସହିତ ସୃଷ୍ଟି',
        'operationFailed': 'କାର୍ଯ୍ୟ ବିଫଳ',
        'confirmDelete': 'ଆପଣ ସତରେ ବିଲୋପ କରିବାକୁ ଚାହୁଁ କି?',
        'cannotBeUndone': 'ଏହି କାର୍ଯ୍ୟ ଫେରାଇ ହୋଇପାରିବ ନାହିଁ.',
    },
}
write_locale('or', or_data)

# ── Malayalam (ml) ────────────────────────────────────────────────────────────
ml_data = {
    'common': {
        'appName': 'വോജാസ്', 'tagline': 'എം.പി.എൽ.എ.ഡി. ഉത്തരവാദിത്വ പ്ലാറ്റ്ഫോം',
        'loading': 'ലോഡ് ചെയ്യുന്നു...', 'error': 'പിശക്', 'success': 'വിജയം',
        'save': 'സംരക്ഷിക്കുക', 'cancel': 'റദ്ദാക്കുക', 'delete': 'ഇല്ലാതാക്കുക', 'edit': 'തിരുത്തുക',
        'create': 'സൃഷ്ടിക്കുക', 'search': 'തിരയുക', 'filter': 'ഫിൽട്ടർ', 'clear': 'മായ്ക്കുക',
        'apply': 'പ്രയോഗിക്കുക', 'back': 'പുറകോട്ട്', 'next': 'അടുത്തത്', 'previous': 'മുമ്പത്തെ',
        'submit': 'സമർപ്പിക്കുക', 'reset': 'പുനഃസജ്ജമാക്കുക', 'confirm': 'സ്ഥിരീകരിക്കുക',
        'close': 'അടയ്ക്കുക', 'view': 'കാണുക', 'download': 'ഡൗൺലോഡ്',
        'upload': 'അപ്‌ലോഡ്', 'refresh': 'പുതുക്കുക', 'retry': 'വീണ്ടും ശ്രമിക്കുക',
        'noData': 'ഡാറ്റയില്ല', 'notFound': 'കണ്ടെത്തിയില്ല',
        'unauthorized': 'അനധികൃതം', 'forbidden': 'നിരോധിച്ചിരിക്കുന്നു',
        'serverError': 'സെർവർ പിശക്', 'networkError': 'നെറ്റ്‌വർക്ക് പിശക്',
        'unknownError': 'അജ്ഞാത പിശക്', 'pageNotFound': 'പേജ് കണ്ടെത്തിയില്ല',
        'goHome': 'ഡാഷ്ബോർഡിലേക്ക് പോകുക', 'language': 'ഭാഷ', 'selectLanguage': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
        'changeLanguage': 'ഭാഷ മാറ്റുക', 'allLanguages': 'എല്ലാ ഭാഷകളും',
        'perPage': 'പേജിന്', 'date': 'തീയതി', 'status': 'നില', 'actions': 'പ്രവൃത്തികൾ',
        'viewAll': 'എല്ലാം കാണുക', 'required': 'ആവശ്യമാണ്', 'optional': 'ഐച്ഛികം',
        'yes': 'ഉവ്വ്', 'no': 'ഇല്ല', 'all': 'എല്ലാം', 'select': 'തിരഞ്ഞെടുക്കുക',
        'selectOption': 'ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക', 'noResults': 'ഫലങ്ങളൊന്നുമില്ല',
        'processing': 'പ്രോസസ്സ് ചെയ്യുന്നു...', 'pending': 'തീർപ്പാക്കാത്തത്',
        'active': 'സജീവം', 'inactive': 'നിഷ്ക്രിയം', 'completed': 'പൂർത്തിയായി',
        'verified': 'പരിശോധിച്ചു', 'rejected': 'നിരസിച്ചു', 'approved': 'അംഗീകരിച്ചു',
        'inProgress': 'പുരോഗമിക്കുന്നു', 'critical': 'ഗുരുതരം', 'high': 'ഉയർന്ന', 'medium': 'ഇടത്തരം',
        'low': 'കുറഞ്ഞ', 'warning': 'മുന്നറിയിപ്പ്', 'danger': 'അപകടം',
        'primary': 'പ്രാഥമികം', 'secondary': 'ദ്വിതീയം', 'login': 'ലോഗിൻ',
        'logout': 'ലോഗൗട്ട്', 'register': 'രജിസ്റ്റർ', 'email': 'ഇമെയിൽ',
        'password': 'പാസ്‌വേഡ്', 'name': 'പേര്', 'description': 'വിവരണം',
        'details': 'വിശദാംശങ്ങൾ', 'type': 'തരം', 'amount': 'തുക', 'count': 'എണ്ണം',
        'value': 'മൂല്യം', 'title': 'തലക്കെട്ട്', 'notes': 'കുറിപ്പുകൾ', 'comment': 'അഭിപ്രായം',
        'comments': 'അഭിപ്രായങ്ങൾ', 'message': 'സന്ദേശം', 'subject': 'വിഷയം', 'reason': 'കാരണം',
        'createdAt': 'സൃഷ്ടിച്ചു', 'updatedAt': 'അപ്ഡേറ്റ് ചെയ്തു', 'lastUpdated': 'അവസാനം അപ്ഡേറ്റ് ചെയ്തത്',
        'ago': 'മുമ്പ്', 'today': 'ഇന്ന്', 'yesterday': 'ഇന്നലെ', 'thisWeek': 'ഈ ആഴ്ച',
        'thisMonth': 'ഈ മാസം', 'lastMonth': 'കഴിഞ്ഞ മാസം', 'lastWeek': 'കഴിഞ്ഞ ആഴ്ച',
        'custom': 'ഇഷ്ടാനുസൃതം', 'dateRange': 'തീയതി പരിധി',
        'startDate': 'ആരംഭ തീയതി', 'endDate': 'അവസാന തീയതി',
        'created': 'സൃഷ്ടിച്ചു', 'updated': 'അപ്ഡേറ്റ് ചെയ്തു', 'deleted': 'ഇല്ലാതാക്കി',
        'by': 'വഴി', 'and': 'ഒപ്പം', 'or': 'അല്ലെങ്കിൽ', 'more': 'കൂടുതൽ', 'less': 'കുറവ്',
        'open': 'തുറക്കുക', 'export': 'കയറ്റുമതി', 'import': 'ഇറക്കുമതി', 'print': 'അച്ചടിക്കുക',
        'copy': 'കോപ്പി', 'copied': 'കോപ്പിയായി!', 'share': 'പങ്കിടുക',
        'compare': 'താരതമ്യം', 'difference': 'വ്യത്യാസം', 'summary': 'സംഗ്രഹം',
        'overview': 'അവലോകനം', 'statistics': 'സ്ഥിതിവിവരക്കണക്കുകൾ', 'analytics': 'വിശകലനം',
        'report': 'റിപ്പോർട്ട്', 'reports': 'റിപ്പോർട്ടുകൾ', 'document': 'രേഖ',
        'documents': 'രേഖകൾ', 'file': 'ഫയൽ', 'files': 'ഫയലുകൾ',
        'attachment': 'അറ്റാച്ച്മെന്റ്', 'version': 'പതിപ്പ്', 'history': 'ചരിത്രം',
        'timeline': 'സമയരേഖ', 'recent': 'സമീപകാലം', 'top': 'മുകളിൽ',
        'newest': 'ഏറ്റവും പുതിയ', 'best': 'മികച്ച', 'worst': 'ഏറ്റവും മോശം',
        'savedSuccessfully': 'വിജയകരമായി സംരക്ഷിച്ചു',
        'deletedSuccessfully': 'വിജയകരമായി ഇല്ലാതാക്കി',
        'updatedSuccessfully': 'വിജയകരമായി അപ്ഡേറ്റ് ചെയ്തു',
        'createdSuccessfully': 'വിജയകരമായി സൃഷ്ടിച്ചു',
        'operationFailed': 'പ്രവർത്തനം പരാജയപ്പെട്ടു',
        'confirmDelete': 'ശരിക്കും ഇല്ലാതാക്കണോ?',
        'cannotBeUndone': 'ഈ പ്രവർത്തനം പഴയപടിയാക്കാൻ കഴിയില്ല.',
    },
}
write_locale('ml', ml_data)
print('Done: ml.json')

# ── Punjabi / Gurmukhi (pa) ───────────────────────────────────────────────────
pa_data = {
    'common': {
        'appName': 'ਵੋਜਾਸ', 'tagline': 'ਐਮ.ਪੀ.ਐਲ.ਏ.ਡੀ. ਜਵਾਬਦੇਹੀ ਪਲੇਟਫਾਰਮ',
        'loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...', 'error': 'ਗਲਤੀ', 'success': 'ਕਾਮਯਾਬ',
        'save': 'ਸੁਰੱਖਿਅਤ ਕਰੋ', 'cancel': 'ਰੱਦ ਕਰੋ', 'delete': 'ਮਿਟਾਓ', 'edit': 'ਸੋਧੋ',
        'create': 'ਬਣਾਓ', 'search': 'ਖੋਜੋ', 'filter': 'ਫਿਲਟਰ', 'clear': 'ਸਾਫ਼ ਕਰੋ',
        'apply': 'ਲਾਗੂ ਕਰੋ', 'back': 'ਵਾਪਸ', 'next': 'ਅਗਲਾ', 'previous': 'ਪਿੱਛਲਾ',
        'submit': 'ਜਮ੍ਹਾਂ ਕਰਵਾਓ', 'reset': 'ਮੁੜ ਸੈੱਟ ਕਰੋ', 'confirm': 'ਪੁਸ਼ਟੀ ਕਰੋ',
        'close': 'ਬੰਦ ਕਰੋ', 'view': 'ਵੇਖੋ', 'download': 'ਡਾਊਨਲੋਡ',
        'upload': 'ਅੱਪਲੋਡ', 'refresh': 'ਤਾਜ਼ਾ ਕਰੋ', 'retry': 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
        'noData': 'ਕੋਈ ਡੇਟਾ ਨਹੀਂ', 'notFound': 'ਨਹੀਂ ਮਿਲਿਆ',
        'unauthorized': 'ਗੈਰ-ਮਨਜ਼ੂਰ', 'forbidden': 'ਪ੍ਰਵੇਸ਼ ਮਨਜ਼ੂਰ ਨਹੀਂ',
        'serverError': 'ਸਰਵਰ ਗਲਤੀ', 'networkError': 'ਨੈੱਟਵਰਕ ਗਲਤੀ',
        'unknownError': 'ਅਣਪਛਾਤਾ ਗਲਤੀ', 'pageNotFound': 'ਸਫ਼ਾ ਨਹੀਂ ਮਿਲਿਆ',
        'goHome': 'ਡੈਸ਼ਬੋਰਡ ਤੇ ਜਾਓ', 'language': 'ਭਾਸ਼ਾ', 'selectLanguage': 'ਭਾਸ਼ਾ ਚੁਣੋ',
        'changeLanguage': 'ਭਾਸ਼ਾ ਬਦਲੋ', 'allLanguages': 'ਸਾਰੀਆਂ ਭਾਸ਼ਾਵਾਂ',
        'perPage': 'ਪ੍ਰਤੀ ਸਫ਼ਾ', 'date': 'ਮਿਤੀ', 'status': 'ਹਾਲਤ', 'actions': 'ਕਾਰਵਾਈ',
        'viewAll': 'ਸਭ ਵੇਖੋ', 'required': 'ਲੋੜੀਂਦਾ', 'optional': 'ਵਿਕਲਪਕ',
        'yes': 'ਹਾਂ', 'no': 'ਨਹੀਂ', 'all': 'ਸਾਰੇ', 'select': 'ਚੁਣੋ',
        'selectOption': 'ਇੱਕ ਚੋਣ ਚੁਣੋ', 'noResults': 'ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ ਮਿਲਿਆ',
        'processing': 'ਪ੍ਰੋਸੈਸਿੰਗ...', 'pending': 'ਅਧੀਨ',
        'active': 'ਸਰਗਰਮ', 'inactive': 'ਨਿਰਵਿਅਕ', 'completed': 'ਮੁਕੰਮਲ',
        'verified': 'ਪ੍ਰਮਾਣਿਤ', 'rejected': 'ਰੱਦ ਕੀਤਾ', 'approved': 'ਮਨਜ਼ੂਰ',
        'inProgress': 'ਜਾਰੀ', 'critical': 'ਗੰਭੀਰ', 'high': 'ਉੱਚ', 'medium': 'ਦਰਮਿਆਨਾ',
        'low': 'ਘੱਟ', 'warning': 'ਚੇਤਾਵਨੀ', 'danger': 'ਖ਼ਤਰਾ',
        'primary': 'ਪ੍ਰਾਥਮਿਕ', 'secondary': 'ਦੂਜਾ', 'login': 'ਲੌਗਇਨ',
        'logout': 'ਲੌਗਆਊਟ', 'register': 'ਰਜਿਸਟਰ', 'email': 'ਈਮੇਲ',
        'password': 'ਪਾਸਵਰਡ', 'name': 'ਨਾਂ', 'description': 'ਵੇਰਵਾ',
        'details': 'ਵਿਸਤ੍ਰਿਤ', 'type': 'ਕਿਸਮ', 'amount': 'ਰਾਸ਼ੀ', 'count': 'ਗਿਣਤੀ',
        'value': 'ਮੁੱਲ', 'title': 'ਸਿਰਲੇਖ', 'notes': 'ਨੋਟਸ', 'comment': 'ਟਿੱਪਣੀ',
        'comments': 'ਟਿੱਪਣੀਆਂ', 'message': 'ਸੁਨੇਹਾ', 'subject': 'ਵਿਸ਼ਾ', 'reason': 'ਕਾਰਨ',
        'createdAt': 'ਬਣਾਇਆ', 'updatedAt': 'ਅੱਪਡੇਟ ਕੀਤਾ', 'lastUpdated': 'ਆਖਰੀ ਅੱਪਡੇਟ',
        'ago': 'ਪਹਿਲਾਂ', 'today': 'ਅੱਜ', 'yesterday': 'ਕੱਲ੍ਹ', 'thisWeek': 'ਇਸ ਹਫ਼ਤੇ',
        'thisMonth': 'ਇਸ ਮਹੀਨੇ', 'lastMonth': 'ਪਿਛਲਾ ਮਹੀਨਾ', 'lastWeek': 'ਪਿਛਲਾ ਹਫ਼ਤਾ',
        'custom': 'ਕਸਟਮ', 'dateRange': 'ਮਿਤੀ ਸੀਮਾ',
        'startDate': 'ਸ਼ੁਰੂ ਮਿਤੀ', 'endDate': 'ਅੰਤ ਮਿਤੀ',
        'created': 'ਬਣਾਇਆ', 'updated': 'ਅੱਪਡੇਟ', 'deleted': 'ਮਿਟਾਇਆ',
        'by': 'ਵੱਲੋਂ', 'and': 'ਅਤੇ', 'or': 'ਜਾਂ', 'more': 'ਹੋਰ', 'less': 'ਘੱਟ',
        'open': 'ਖੋਲ੍ਹੋ', 'export': 'ਨਿਰਯਾਤ', 'import': 'ਆਯਾਤ', 'print': 'ਪ੍ਰਿੰਟ',
        'copy': 'ਕਾਪੀ', 'copied': 'ਕਾਪੀ ਹੋ ਗਈ!', 'share': 'ਸ਼ੇਅਰ',
        'compare': 'ਤੁਲਨਾ', 'difference': 'ਫਰਕ', 'summary': 'ਸੰਕੇਤ',
        'overview': 'ਸਮੀਖਿਆ', 'statistics': 'ਅੰਕੜੇ', 'analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ',
        'report': 'ਰਿਪੋਰਟ', 'reports': 'ਰਿਪੋਰਟਾਂ', 'document': 'ਦਸਤਾਵੇਜ',
        'documents': 'ਦਸਤਾਵੇਜਾਂ', 'file': 'ਫਾਈਲ', 'files': 'ਫਾਈਲਾਂ',
        'attachment': 'ਮੁਲੱਬਤ', 'version': 'ਸੰਸਕਰਣ', 'history': 'ਇਤਿਹਾਸ',
        'timeline': 'ਟਾਈਮਲਾਈਨ', 'recent': 'ਤਾਜ਼ਾ', 'top': 'ਸਿਖ਼ਰ',
        'newest': 'ਨਵਾਂ', 'best': 'ਬੁਰਾ', 'worst': 'ਸਭ ਤੋਂ ਮਾੜਾ',
        'savedSuccessfully': 'ਕਾਮਯਾਬੀ ਨਾਲ ਸੁਰੱਖਿਅਤ ਕੀਤਾ',
        'deletedSuccessfully': 'ਕਾਮਯਾਬੀ ਨਾਲ ਮਿਟਾਇਆ',
        'updatedSuccessfully': 'ਕਾਮਯਾਬੀ ਨਾਲ ਅੱਪਡੇਟ ਕੀਤਾ',
        'createdSuccessfully': 'ਕਾਮਯਾਬੀ ਨਾਲ ਬਣਾਇਆ',
        'operationFailed': 'ਕਾਰਵਾਈ ਅਸਫਲ',
        'confirmDelete': 'ਕੀ ਤੁਸੀਂ ਸੱਚਮੁੱਚ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
        'cannotBeUndone': 'ਇਹ ਕਾਰਵਾਈ ਵਾਪਸ ਨਹੀਂ ਲਈ ਜਾ ਸਕਦੀ.',
    },
}
write_locale('pa', pa_data)
print('Done: pa.json')

# ── Assamese (as) ────────────────────────────────────────────────────────────
as_data = {
    'common': {
        'appName': 'ৱোজাছ', 'tagline': 'এম.পি.এল.এ.ডি. উত্তৰদায়িত্ব প্লেটফর্ম',
        'loading': 'লোড হৈ আছে...', 'error': 'ত্রুটি', 'success': 'সফল',
        'save': 'সাঁচক', 'cancel': 'বাতিল', 'delete': 'মচক', 'edit': 'সম্পাদনা',
        'create': 'সৃষ্টিক', 'search': 'সন্ধান', 'filter': 'ফিল্টাৰ', 'clear': 'পৰিষ্কাৰ',
        'apply': 'প্রয়োগ', 'back': 'উভতি যাওক', 'next': 'পিছল', 'previous': 'আগৰ',
        'submit': 'দাখিল', 'reset': 'পুনৰগঠন', 'confirm': 'নিশ্চিতকৰণ',
        'close': 'বন্ধ', 'view': 'চাওক', 'download': 'ডাউনলোড',
        'upload': 'আপলোড', 'refresh': 'তাজা', 'retry': 'পুনৰ চেষ্টা',
        'noData': 'কোনো তথ্য নাই', 'notFound': 'পোৱা নাযায়',
        'unauthorized': 'অনুমোদন নাই', 'forbidden': 'প্রৱেশ নিষিদ্ধ',
        'serverError': 'চাৰ্ভাৰ ত্রুটি', 'networkError': 'নেটৱৰ্ক ত্রুটি',
        'unknownError': 'অজ্ঞাত ত্রুটি', 'pageNotFound': 'পৃষ্ঠা পোৱা নাযায়',
        'goHome': 'ডেশবোর্ডলৈ যাওক', 'language': 'ভাষা', 'selectLanguage': 'ভাষা বাছি লওক',
        'changeLanguage': 'ভাষা সলনি কৰক', 'allLanguages': 'সকলো ভাষা',
        'perPage': 'প্রতি পৃষ্ঠা', 'date': 'তাৰিখ', 'status': 'অৱস্থা', 'actions': 'কার্য',
        'viewAll': 'সকলো চাওক', 'required': 'প্রয়োজনীয়', 'optional': 'ঐচ্ছিক',
        'yes': 'হয়', 'no': 'নহয়', 'all': 'সকলো', 'select': 'বাছি লওক',
        'selectOption': 'এটা বিকল্প বাছি লওক', 'noResults': 'কোনো ফলাফল পোৱা নাযায়',
        'processing': 'প্রক্রিয়া চলিছে...', 'pending': 'বিবেচনাধীন',
        'active': 'সক্রিয়', 'inactive': 'নিষ্ক্রিয়', 'completed': 'সম্পূর্ণ',
        'verified': 'প্রমাণিত', 'rejected': 'প্রত্যাখ্যান', 'approved': 'অনুমোদিত',
        'inProgress': 'চলমান', 'critical': 'গুৰুতৰ', 'high': 'উচ্চ', 'medium': 'মধ্যম',
        'low': 'নিম্ন', 'warning': 'সতর্কতা', 'danger': 'বিপদ',
        'primary': 'প্রাথমিক', 'secondary': 'দ্বিতীয়', 'login': 'লগইন',
        'logout': 'লগআউট', 'register': 'পঞ্জীয়ন', 'email': 'ইমেইল',
        'password': 'পাছৱার্ড', 'name': 'নাম', 'description': 'বিৱৰণ',
        'details': 'বিশদ', 'type': 'প্রকাৰ', 'amount': 'পরিমাণ', 'count': 'গণনা',
        'value': 'মূল্য', 'title': 'শীর্ষক', 'notes': 'টোকা', 'comment': 'মন্তব্য',
        'comments': 'মন্তব্যসমূহ', 'message': 'বার্তা', 'subject': 'বিষয়', 'reason': 'কাৰণ',
        'createdAt': 'সৃষ্টি হৈছে', 'updatedAt': 'আপডেট হৈছে', 'lastUpdated': 'চূড়ান্ত আপডেট',
        'ago': 'আগত', 'today': 'আজি', 'yesterday': 'কালি', 'thisWeek': 'এই সপ্তাহত',
        'thisMonth': 'এই মাহত', 'lastMonth': 'বিগত মাহ', 'lastWeek': 'বিগত সপ্তাহ',
        'custom': 'কাষ্টম', 'dateRange': 'তাৰিখৰ পৰিসৰ',
        'startDate': 'আৰম্ভৰ তাৰিখ', 'endDate': 'শেষৰ তাৰিখ',
        'created': 'সৃষ্টি', 'updated': 'আপডেট', 'deleted': 'মচা',
        'by': 'দ্বাৰা', 'and': 'আৰু', 'or': 'বা', 'more': 'বেছি', 'less': 'কম',
        'open': 'খোলক', 'export': 'ৰপ্তানি', 'import': 'আমদানি', 'print': 'ছপা',
        'copy': 'কপি', 'copied': 'কপি হৈছে!', 'share': 'শ্বেয়াৰ',
        'compare': 'তুলনা', 'difference': 'পার্থক্য', 'summary': 'সাৰসংক্ষেপ',
        'overview': 'অভিৱীক্ষণ', 'statistics': 'পৰিসংখ্যান', 'analytics': 'বিশ্লেষণ',
        'report': 'প্রতিবেদন', 'reports': 'প্রতিবেদনসমূহ', 'document': 'দলিল',
        'documents': 'দলিলসমূহ', 'file': 'ফাইল', 'files': 'ফাইলসমূহ',
        'attachment': 'সংলগ্ন', 'version': 'সংস্কৰণ', 'history': 'ইতিহাস',
        'timeline': 'সময়ৰেখা', 'recent': 'সাম্প্রতিক', 'top': 'শীর্ষ',
        'newest': 'নতুন', 'best': 'উত্তম', 'worst': 'কুৰূষ্টম',
        'savedSuccessfully': 'সফলতাৰে সাঁচক হৈছে',
        'deletedSuccessfully': 'সফলতাৰে মচা হৈছে',
        'updatedSuccessfully': 'সফলতাৰে আপডেট হৈছে',
        'createdSuccessfully': 'সফলতাৰে সৃষ্টি হৈছে',
        'operationFailed': 'কার্য ব্যর্থ',
        'confirmDelete': 'আপুনি সত্যাই মচিব বিচাৰে নেকি?',
        'cannotBeUndone': 'এই কার্য ঘূৰাই অনা সম্ভব নহয়.',
    },
}
write_locale('as', as_data)
print('Done: as.json')

# ── Maithili (mai) ────────────────────────────────────────────────────────────
mai_data = {
    'common': {
        'appName': 'वोजास', 'tagline': 'एम.पी.एल.ए.डी. जबाबदेही प्लेटफार्म',
        'loading': 'लोडिंग...', 'error': 'त्रुटि', 'success': 'सफल',
        'save': 'सहेजू', 'cancel': 'रद्द करू', 'delete': 'मेटाब', 'edit': 'संपादित करू',
        'create': 'बनाब', 'search': 'खोजू', 'filter': 'फिल्टर', 'clear': 'साफ करू',
        'apply': 'लागू करू', 'back': 'पाछा', 'next': 'अगिल', 'previous': 'पूर्ववर्ती',
        'submit': 'जमा करू', 'reset': 'रीसेट', 'confirm': 'पुष्टि करू',
        'close': 'बंद करू', 'view': 'देखू', 'download': 'डाउनलोड',
        'upload': 'अपलोड', 'refresh': 'ताजा करू', 'retry': 'पुनः प्रयास',
        'noData': 'कोनो डेटा नहि', 'notFound': 'नहि भेटल',
        'unauthorized': 'अनधिकृत', 'forbidden': 'प्रवेश निषेध',
        'serverError': 'सर्वर त्रुटि', 'networkError': 'नेटवर्क त्रुटि',
        'unknownError': 'अज्ञात त्रुटि', 'pageNotFound': 'पृष्ठ नहि भेटल',
        'goHome': 'डैशबोर्ड पर जाउ', 'language': 'भाषा', 'selectLanguage': 'भाषा चुनू',
        'changeLanguage': 'भाषा बदलू', 'allLanguages': 'सभ भाषा',
        'perPage': 'प्रति पृष्ठ', 'date': 'तारीख', 'status': 'स्थिति', 'actions': 'कार्य',
        'viewAll': 'सभ देखू', 'required': 'आवश्यक', 'optional': 'वैकल्पिक',
        'yes': 'हाँ', 'no': 'नहि', 'all': 'सभ', 'select': 'चुनू',
        'selectOption': 'एकटा विकल्प चुनू', 'noResults': 'कोनो परिणाम नहि',
        'processing': 'प्रक्रिया चलि रहल...', 'pending': 'विचाराधीन',
        'active': 'सक्रिय', 'inactive': 'निष्क्रिय', 'completed': 'पूर्ण',
        'verified': 'सत्यापित', 'rejected': 'अस्वीकृत', 'approved': 'स्वीकृत',
        'inProgress': 'जारी', 'critical': 'गंभीर', 'high': 'उच्च', 'medium': 'मध्यम',
        'low': 'कम', 'warning': 'चेतावनी', 'danger': 'खतरा',
        'primary': 'प्राथमिक', 'secondary': 'द्वितीयक', 'login': 'लॉगिन',
        'logout': 'लॉगआउट', 'register': 'पंजीकरण', 'email': 'ईमेल',
        'password': 'पासवर्ड', 'name': 'नाम', 'description': 'विवरण',
        'details': 'विस्तृत', 'type': 'प्रकार', 'amount': 'राशि', 'count': 'गणना',
        'value': 'मूल्य', 'title': 'शीर्षक', 'notes': 'नोट्स', 'comment': 'टिप्पणी',
        'comments': 'टिप्पणीसभ', 'message': 'संदेश', 'subject': 'विषय', 'reason': 'कारण',
        'createdAt': 'बनाओल गेल', 'updatedAt': 'अपडेट कएल गेल', 'lastUpdated': 'अंतिम अपडेट',
        'ago': 'पहिले', 'today': 'आज', 'yesterday': 'काल', 'thisWeek': 'एहि सप्ताह',
        'thisMonth': 'एहि महिना', 'lastMonth': 'पूर्व महिना', 'lastWeek': 'पूर्व सप्ताह',
        'custom': 'कस्टम', 'dateRange': 'तारीख रेंज',
        'startDate': 'आरम्भ तारीख', 'endDate': 'समाप्ति तारीख',
        'created': 'बनाओल', 'updated': 'अपडेट', 'deleted': 'मेटाब',
        'by': 'द्वारा', 'and': 'आरू', 'or': 'या', 'more': 'अउरी', 'less': 'कम',
        'open': 'खोलू', 'export': 'निर्यात', 'import': 'आयात', 'print': 'छापू',
        'copy': 'कॉपी', 'copied': 'कॉपी भ गेल!', 'share': 'शेयर',
        'compare': 'तुलना', 'difference': 'अंतर', 'summary': 'सारांश',
        'overview': 'अवलोकन', 'statistics': 'आंकड़ासभ', 'analytics': 'विश्लेषण',
        'report': 'रिपोर्ट', 'reports': 'रिपोर्टसभ', 'document': 'दस्तावेज',
        'documents': 'दस्तावेजसभ', 'file': 'फाइल', 'files': 'फाइलसभ',
        'attachment': 'संलग्नक', 'version': 'संस्करण', 'history': 'इतिहास',
        'timeline': 'समयरेखा', 'recent': 'हालिया', 'top': 'शीर्ष',
        'newest': 'नवीन', 'best': 'सर्वश्रेष्ठ', 'worst': 'सर्वाधिक खराब',
        'savedSuccessfully': 'सफलतापूर्वक सहेजल गेल',
        'deletedSuccessfully': 'सफलतापूर्वक मेटाओल गेल',
        'updatedSuccessfully': 'सफलतापूर्वक अपडेट कएल गेल',
        'createdSuccessfully': 'सफलतापूर्वक बनाओल गेल',
        'operationFailed': 'कार्य विफल',
        'confirmDelete': 'अहाँ सच्चमुख मेटाब चाहैत छी?',
        'cannotBeUndone': 'ई कार्य पूर्ववत नहि कएल जा सकैत.',
    },
}
write_locale('mai', mai_data)
print('Done: mai.json')

# ── Sanskrit (sa) ────────────────────────────────────────────────────────────
sa_data = {
    'common': {
        'appName': 'वोजास्', 'tagline': 'एम्पीएलएडी उत्तरदायित्वप्लेटफॉर्म',
        'loading': 'लोडिंग्...', 'error': 'दोषः', 'success': 'सफलम्',
        'save': 'संरक्ष्यताम्', 'cancel': 'निरस्तम्', 'delete': 'विलोप्यताम्', 'edit': 'सम्पाद्यताम्',
        'create': 'निर्मीयताम्', 'search': 'अन्वेष्यताम्', 'filter': 'फिल्टरम्', 'clear': 'शोध्यताम्',
        'apply': 'प्रयोज्यताम्', 'back': 'पश्चात्', 'next': 'अग्रिमः', 'previous': 'पूर्ववर्ती',
        'submit': 'समर्प्यताम्', 'reset': 'पुनर्निर्मीयताम्', 'confirm': 'स्वीक्रियताम्',
        'close': 'बध्यताम्', 'view': 'दृश्यताम्', 'download': 'डाउनलोड्',
        'upload': 'अपलोड्', 'refresh': 'नवीकरणम्', 'retry': 'पुनःप्रयासः',
        'noData': 'कोऽप्यानुदानं नास्ति', 'notFound': 'न प्राप्तम्',
        'unauthorized': 'अनधिकृतः', 'forbidden': 'प्रवेशनिषेधः',
        'serverError': 'सर्वरदोषः', 'networkError': 'नेटवर्कदोषः',
        'unknownError': 'अज्ञातदोषः', 'pageNotFound': 'पृष्ठं न प्राप्तम्',
        'goHome': 'डैशबोर्डं प्रति गच्छतु', 'language': 'भाषा', 'selectLanguage': 'भाषां वृणुताम्',
        'changeLanguage': 'भाषां परिवर्त्यताम्', 'allLanguages': 'सर्वाभाषाः',
        'perPage': 'प्रति पृष्ठम्', 'date': 'तिथिः', 'status': 'स्थितिः', 'actions': 'क्रियाः',
        'viewAll': 'सर्वं पश्यन्तु', 'required': 'आवश्यकम्', 'optional': 'वैकल्पिकम्',
        'yes': 'अस्तु', 'no': 'न', 'all': 'सर्वे', 'select': 'वृणुताम्',
        'selectOption': 'एकं विकल्पं वृणुताम्', 'noResults': 'कोऽप्यानुभवः न प्राप्तः',
        'processing': 'प्रक्रियायाम्...', 'pending': 'विचाराधीना',
        'active': 'सक्रियः', 'inactive': 'निष्क्रियः', 'completed': 'समाप्तः',
        'verified': 'सत्यापितः', 'rejected': 'प्रत्याख्यातः', 'approved': 'स्वीकृतः',
        'inProgress': 'प्रगतिः', 'critical': 'गभीरः', 'high': 'उच्चः', 'medium': 'मध्यमः',
        'low': 'न्यूनः', 'warning': 'सावधानिः', 'danger': 'जोखिमा',
        'primary': 'प्राथमिकः', 'secondary': 'द्वितीयकः', 'login': 'लॉगिन्',
        'logout': 'लॉगआउट्', 'register': 'पञ्जीकरणम्', 'email': 'ईमेल्',
        'password': 'पासवर्ड्', 'name': 'नाम', 'description': 'विवरणम्',
        'details': 'विस्तृतम्', 'type': 'प्रकारः', 'amount': 'राशिः', 'count': 'गणना',
        'value': 'मूल्यम्', 'title': 'शीर्षकम्', 'notes': 'टिप्पणीनि', 'comment': 'अभिप्रायः',
        'comments': 'अभिप्रायाः', 'message': 'सन्देशः', 'subject': 'विषयः', 'reason': 'कारणम्',
        'createdAt': 'निर्मितम्', 'updatedAt': 'अद्यतनीकृतम्', 'lastUpdated': 'अन्तिमअद्यतनीकरणम्',
        'ago': 'पूर्वम्', 'today': 'अद्य', 'yesterday': 'ह्यः', 'thisWeek': 'अस्मिन् सप्ताहे',
        'thisMonth': 'अस्मिन् मासे', 'lastMonth': 'गतमासे', 'lastWeek': 'गतसप्ताहे',
        'custom': 'रूढिः', 'dateRange': 'तिथिपरिधिः',
        'startDate': 'आरम्भतिथिः', 'endDate': 'समाप्तितिथिः',
        'created': 'निर्मितम्', 'updated': 'अद्यतनीकृतम्', 'deleted': 'विलोपितम्',
        'by': 'द्वारा', 'and': 'च', 'or': 'वा', 'more': 'अधिकम्', 'less': 'न्यूनम्',
        'open': 'उद्घाट्यताम्', 'export': 'निर्यातः', 'import': 'आयातः', 'print': 'मुद्रणम्',
        'copy': 'प्रतिलिपिः', 'copied': 'प्रतिलिपिः कृता!', 'share': 'विभज्यताम्',
        'compare': 'तुलनम्', 'difference': 'भेदः', 'summary': 'सारांशः',
        'overview': 'परिदृश्यम्', 'statistics': 'सांख्यिकी', 'analytics': 'विश्लेषणम्',
        'report': 'प्रतिवेदनम्', 'reports': 'प्रतिवेदनानि', 'document': 'प्रमाणपत्रम्',
        'documents': 'प्रमाणपत्राणि', 'file': 'संचिका', 'files': 'संचिकाः',
        'attachment': 'संलग्नकम्', 'version': 'संस्करणम्', 'history': 'इतिहासः',
        'timeline': 'कालरेखा', 'recent': 'अर्वाचीनः', 'top': 'शिखरम्',
        'newest': 'नवीनतमः', 'best': 'उत्तमः', 'worst': 'अधमतमः',
        'savedSuccessfully': 'सफलतया संरक्षितम्',
        'deletedSuccessfully': 'सफलतया विलोपितम्',
        'updatedSuccessfully': 'सफलतया अद्यतनीकृतम्',
        'createdSuccessfully': 'सफलतया निर्मितम्',
        'operationFailed': 'क्रिया असफला',
        'confirmDelete': 'विदधाति वै? वास्तविकं विलोपनम्',
        'cannotBeUndone': 'इयं क्रिया प्रतिनिवर्त्य न शक्यते.',
    },
}
write_locale('sa', sa_data)
print('Done: sa.json')

# ── Konkani / Devanagari (gom) ───────────────────────────────────────────────
gom_data = {
    'common': {
        'appName': 'वोजास', 'tagline': 'एम.पी.एल.ए.डी. जबाबदेकारी प्लेटफॉर्म',
        'loading': 'लोडिंग...', 'error': 'त्रुटि', 'success': 'यशस्वी',
        'save': 'जतन', 'cancel': 'रद्द', 'delete': 'मेटव', 'edit': 'संपादन',
        'create': 'तयार करव', 'search': 'सोधपं', 'filter': 'फिल्टर', 'clear': 'साफ करव',
        'apply': 'लागू करव', 'back': 'माग', 'next': 'पयलें', 'previous': 'फुडलें',
        'submit': 'जमा करव', 'reset': 'रीसेट', 'confirm': 'खरेदी करव',
        'close': 'बंद करव', 'view': 'पळयेव', 'download': 'डाउनलोड',
        'upload': 'अपलोड', 'refresh': 'रिफ्रेश', 'retry': 'पुनः प्रयत्न',
        'noData': 'कोय आकडो ना', 'notFound': 'सापडलें ना',
        'unauthorized': 'अनधिकृत', 'forbidden': 'प्रवेश निषेध',
        'serverError': 'सर्वर त्रुटि', 'networkError': 'नेटवर्क त्रुटि',
        'unknownError': 'अज्ञात त्रुटि', 'pageNotFound': 'पान सापडलें ना',
        'goHome': 'डैशबोर्डार जा', 'language': 'भास', 'selectLanguage': 'भास वयल करव',
        'changeLanguage': 'भास बदलव', 'allLanguages': 'सगले भास',
        'perPage': 'प्रति पान', 'date': 'तारीख', 'status': 'स्थिती', 'actions': 'कामां',
        'viewAll': 'सगलें पळयेव', 'required': 'आवश्यक', 'optional': 'वैकल्पिक',
        'yes': 'हांव', 'no': 'नां', 'all': 'सगलें', 'select': 'वयल करव',
        'selectOption': 'एक विकल्प वयल करव', 'noResults': 'कोय निकाल सापडलो ना',
        'processing': 'प्रक्रिया चालु आहे...', 'pending': 'विचाराधीन',
        'active': 'सक्रिय', 'inactive': 'निष्क्रिय', 'completed': 'पूर्ण',
        'verified': 'खरेदी केल्लें', 'rejected': 'नकारलें', 'approved': 'मंजूर केल्लें',
        'inProgress': 'चालू आहे', 'critical': 'गंभीर', 'high': 'उंच', 'medium': 'मध्यम',
        'low': 'उणें', 'warning': 'इशारो', 'danger': 'धोको',
        'primary': 'मुख्य', 'secondary': 'दुसरें', 'login': 'लॉगिन',
        'logout': 'लॉगआउट', 'register': 'नोंदणी', 'email': 'इमेल',
        'password': 'पासवर्ड', 'name': 'नांव', 'description': 'वर्णन',
        'details': 'तपशील', 'type': 'प्रकार', 'amount': 'रक्कम', 'count': 'गणना',
        'value': 'किंमत', 'title': 'शीर्षक', 'notes': 'टिप्पणी', 'comment': 'टीक',
        'comments': 'टीकां', 'message': 'संदेश', 'subject': 'विषय', 'reason': 'कारण',
        'createdAt': 'तयार केल्लें', 'updatedAt': 'अद्यतन केल्लें', 'lastUpdated': 'शेवटचें अद्यतन',
        'ago': 'आदीं', 'today': 'आयज', 'yesterday': 'काल', 'thisWeek': 'ह्या आदवे',
        'thisMonth': 'ह्या म्हयन्यां', 'lastMonth': 'फाटल्या म्हयन्यां', 'lastWeek': 'फाटल्या आदवे',
        'custom': 'कस्टम', 'dateRange': 'तारीख श्रेणी',
        'startDate': 'सुरवात तारीख', 'endDate': 'शेवट तारीख',
        'created': 'तयार केल्लें', 'updated': 'अद्यतन', 'deleted': 'मेटल्लें',
        'by': 'ह之道', 'and': 'आनी', 'or': 'वा', 'more': 'उणें', 'less': 'वेळ',
        'open': 'उकताव', 'export': 'निर्यात', 'import': 'आयात', 'print': 'छापणें',
        'copy': 'कॉपी', 'copied': 'कॉपी जालां!', 'share': 'शेअर करव',
        'compare': 'तुलना', 'difference': 'फरक', 'summary': 'सारांश',
        'overview': 'परिक्शण', 'statistics': 'आंकडे', 'analytics': 'विश्लेषण',
        'report': 'अहवाल', 'reports': 'अहवालां', 'document': 'दस्तावेज',
        'documents': 'दस्तावेजां', 'file': 'फाइल', 'files': 'फाइलां',
        'attachment': 'संलग्न', 'version': 'आवृत्ती', 'history': 'इतिहास',
        'timeline': 'काळरेषा', 'recent': 'अलीकडलें', 'top': 'शीर्ष',
        'newest': 'नवो', 'best': 'सोबयल्लें', 'worst': 'वायटल्लें',
        'savedSuccessfully': 'यशस्वीरित्या जतन केल्लें',
        'deletedSuccessfully': 'यशस्वीरित्या मेटल्लें',
        'updatedSuccessfully': 'यशस्वीरित्या अद्यतन केल्लें',
        'createdSuccessfully': 'यशस्वीरित्या तयार केल्लें',
        'operationFailed': 'काम फेल',
        'confirmDelete': 'तूझें खरेंच मेटपां?',
        'cannotBeUndone': 'हें काम मागिं घेवं शकत ना.',
    },
}
write_locale('gom', gom_data)
print('Done: gom.json')

# ── Dogri (doi) ──────────────────────────────────────────────────────────────
doi_data = {
    'common': {
        'appName': 'वोजास', 'tagline': 'एम.पी.एल.ए.डी. जवाबदेही प्लैटफॉर्म',
        'loading': 'लोडिंग...', 'error': 'गलती', 'success': 'सफल',
        'save': 'सैव करो', 'cancel': 'रद्द करो', 'delete': 'मिटाओ', 'edit': 'एडिट करो',
        'create': 'बणाओ', 'search': 'खोजो', 'filter': 'फिल्टर', 'clear': 'साफ करो',
        'apply': 'लागू करो', 'back': 'पीछे', 'next': 'अगला', 'previous': 'पिछला',
        'submit': 'जमा कराओ', 'reset': 'रीसेट', 'confirm': 'पुष्टि करो',
        'close': 'बंद करो', 'view': 'देखो', 'download': 'डाउनलोड',
        'upload': 'अपलोड', 'refresh': 'रिफ्रेश', 'retry': 'फिर कोशिश',
        'noData': 'कोई डेटा नै', 'notFound': 'नै मिल्ला',
        'unauthorized': 'गैर-अधिकृत', 'forbidden': 'प्रवेश मना',
        'serverError': 'सर्वर गलती', 'networkError': 'नेटवर्क गलती',
        'unknownError': 'अज्ञात गलती', 'pageNotFound': 'पेज नै मिल्ली',
        'goHome': 'डैशबोर्ड पर जा', 'language': 'भाषा', 'selectLanguage': 'भाषा चुनो',
        'changeLanguage': 'भाषा बदलो', 'allLanguages': 'सभ भाषाएं',
        'perPage': 'प्रति पेज', 'date': 'तारीख', 'status': 'हालत', 'actions': 'कार्रवाई',
        'viewAll': 'सभ देखो', 'required': 'जरूरी', 'optional': 'वैकल्पिक',
        'yes': 'हां', 'no': 'नै', 'all': 'सभ', 'select': 'चुनो',
        'selectOption': 'एक विकल्प चुनो', 'noResults': 'कोई नतीजा नै',
        'processing': 'प्रोसेसिंग...', 'pending': 'विचाराधीन',
        'active': 'सक्रिय', 'inactive': 'निष्क्रिय', 'completed': 'पूर्ण',
        'verified': 'सत्यापित', 'rejected': 'अस्वीकृत', 'approved': 'मंजूर',
        'inProgress': 'जारी', 'critical': 'गंभीर', 'high': 'उच्च', 'medium': 'मध्यम',
        'low': 'निम्न', 'warning': 'चेतावनी', 'danger': 'खतरा',
        'primary': 'मुख्य', 'secondary': 'द्वितीयक', 'login': 'लॉगिन',
        'logout': 'लॉगआउट', 'register': 'रजिस्टर', 'email': 'ईमेल',
        'password': 'पासवर्ड', 'name': 'नां', 'description': 'विवरण',
        'details': 'विस्तृत', 'type': 'प्रकार', 'amount': 'राशि', 'count': 'गणना',
        'value': 'मूल्य', 'title': 'शीर्षक', 'notes': 'नोट्स', 'comment': 'टिप्पणी',
        'comments': 'टिप्पणियां', 'message': 'संदेश', 'subject': 'विषय', 'reason': 'कारण',
        'createdAt': 'बणाई गई', 'updatedAt': 'अपडेट किया', 'lastUpdated': 'आखरी अपडेट',
        'ago': 'पहलें', 'today': 'आज', 'yesterday': 'कल', 'thisWeek': 'इस हफ्ते',
        'thisMonth': 'इस महीने', 'lastMonth': 'पिछले महीने', 'lastWeek': 'पिछले हफ्ते',
        'custom': 'कस्टम', 'dateRange': 'तारीख रेंज',
        'startDate': 'शुरुआत तारीख', 'endDate': 'अंत तारीख',
        'created': 'बणाई', 'updated': 'अपडेट', 'deleted': 'मिटाई',
        'by': 'द्वारा', 'and': 'और', 'or': 'या', 'more': 'और', 'less': 'कम',
        'open': 'खोलो', 'export': 'निर्यात', 'import': 'आयात', 'print': 'छापो',
        'copy': 'कॉपी', 'copied': 'कॉपी हो गई!', 'share': 'शेयर करो',
        'compare': 'तुलना', 'difference': 'अंतर', 'summary': 'सारांश',
        'overview': 'अवलोकन', 'statistics': 'आंकड़े', 'analytics': 'विश्लेषण',
        'report': 'रिपोर्ट', 'reports': 'रिपोर्टां', 'document': 'दस्तावेज',
        'documents': 'दस्तावेज', 'file': 'फाइल', 'files': 'फाइलां',
        'attachment': 'संलग्न', 'version': 'संस्करण', 'history': 'इतिहास',
        'timeline': 'टाइमलाइन', 'recent': 'हालिया', 'top': 'शीर्ष',
        'newest': 'नवीन', 'best': 'बेस्ट', 'worst': 'वर्स्ट',
        'savedSuccessfully': 'सफलतापूर्वक सैव किया',
        'deletedSuccessfully': 'सफलतापूर्वक मिटाया',
        'updatedSuccessfully': 'सफलतापूर्वक अपडेट किया',
        'createdSuccessfully': 'सफलतापूर्वक बणाया',
        'operationFailed': 'कार्रवाई असफल',
        'confirmDelete': 'क्या तू सचमुच मिटाना चाहदा है?',
        'cannotBeUndone': 'इ कार्रवाई वापस नै की जा सकती.',
    },
}
write_locale('doi', doi_data)
print('Done: doi.json')

# ── Manipuri / Meitei (mni) ─────────────────────────────────────────────────
mni_data = {
    'common': {
        'appName': 'ꯚꯝꯖꯥꯁ', 'tagline': 'ꯑ꯭ꯇꯤ.ꯑ꯭ꯇꯤ.ꯑ꯭ꯇꯤ.ꯖꯤ. ꯑꯁꯤꯒꯤ ꯃꯁꯤꯡꯂꯣꯟ ꯇꯝꯕꯜꯐꯣꯔꯝ',
        'loading': 'ꯂꯣꯗꯤꯡ ꯑꯃꯅꯤ...', 'error': 'ꯌꯦꯡꯕ', 'success': 'ꯁꯛꯄꯅꯤ',
        'save': 'ꯁꯦꯝꯕ', 'cancel': 'ꯆꯥꯟꯕ', 'delete': 'ꯁꯤꯖꯔꯤꯕ', 'edit': 'ꯁꯤꯆꯥꯟꯕ',
        'create': 'ꯃꯤꯡꯂꯤꯕ', 'search': 'ꯁꯧꯔꯤꯕ', 'filter': 'ꯐꯤꯂ꯭ꯠꯔꯤꯕ', 'clear': 'ꯁꯥꯐꯝꯕ',
        'apply': 'ꯂꯨꯞꯊꯣꯛꯂꯤꯕ', 'back': 'ꯂꯝꯕ', 'next': 'ꯁꯛꯅꯕ', 'previous': 'ꯐꯣꯡꯕ',
        'submit': 'ꯁꯝꯖꯤꯔꯤꯕ', 'reset': 'ꯔꯤꯁꯦꯠ', 'confirm': 'ꯁꯤꯖꯁꯤꯟꯂꯤꯕ',
        'close': 'ꯁꯦꯟꯂꯤꯕ', 'view': 'ꯃꯤꯑꯣꯔꯤꯕ', 'download': 'ꯗꯥꯎꯅꯂꯣꯗ꯭',
        'upload': 'ꯑꯞꯂꯣꯗ꯭', 'refresh': 'ꯔꯤꯐ꯭ꯔꯦꯁ꯭', 'retry': 'ꯁꯛꯅꯂꯤꯕ',
        'noData': 'ꯍꯧꯔꯤꯡ ꯑꯁꯤ ꯑꯃꯅꯤ', 'notFound': 'ꯃꯤꯑꯣꯔꯤꯕ ꯑꯃꯅꯤ',
        'unauthorized': 'ꯍꯧꯁꯤꯡ ꯑꯁꯤ ꯑꯣꯏ', 'forbidden': 'ꯃꯤꯑꯣꯔꯤꯕ ꯁꯤꯖꯔꯤꯅꯤ',
        'serverError': 'ꯁꯔꯚꯔ ꯌꯦꯡꯕ', 'networkError': 'ꯅꯦꯠꯈꯣꯡ ꯌꯦꯡꯕ',
        'unknownError': 'ꯍꯧꯁꯤꯡꯒꯤ ꯌꯦꯡꯕ', 'pageNotFound': 'ꯄꯦꯖꯅꯤ ꯃꯤꯑꯣꯔꯤꯕ ꯑꯃꯅꯤ',
        'goHome': 'ꯓ꯭ꯔꯥꯁꯄꯣꯔꯜ ꯑꯁꯤꯒꯤ ꯁꯛ ꯃꯤꯑꯣꯔꯤꯕ', 'language': 'ꯃꯤꯇꯩ', 'selectLanguage': 'ꯃꯤꯇꯩ ꯈꯪꯂꯤꯕ',
        'changeLanguage': 'ꯃꯤꯇꯩ ꯄꯨꯝꯕ', 'allLanguages': 'ꯁꯤꯖꯁꯤꯟꯕ ꯃꯤꯇꯩꯁꯤꯡ',
        'perPage': 'ꯄꯔ ꯄꯦꯖꯒꯤ', 'date': 'ꯂꯧꯁꯤꯡ', 'status': 'ꯁꯤꯖꯁꯤꯟ', 'actions': 'ꯁꯤꯆꯥꯟꯕꯁꯤꯡ',
        'viewAll': 'ꯁꯤꯖꯁꯤꯟꯕ ꯃꯤꯑꯣꯔꯤꯕ', 'required': 'ꯁꯤꯖꯁꯤꯟꯕ', 'optional': 'ꯈꯣꯟꯕ',
        'yes': 'ꯑꯆꯧꯅꯤ', 'no': 'ꯑꯃꯅꯤ', 'all': 'ꯁꯤꯖꯁꯤꯟꯕ', 'select': 'ꯈꯪꯂꯤꯕ',
        'selectOption': 'ꯋꯤꯀꯤ ꯈꯪꯂꯤꯕ', 'noResults': 'ꯍꯧꯔꯤꯡ ꯁꯤꯖꯁꯤꯟꯕ ꯑꯁꯤ ꯑꯃꯅꯤ',
        'processing': 'ꯁꯤꯆꯥꯟꯕ ꯑꯃꯅꯤ...', 'pending': 'ꯃꯤꯑꯣꯔꯤꯕ ꯁꯤꯖꯁꯤꯟꯒꯤ',
        'active': 'ꯁꯛꯄꯅꯤ', 'inactive': 'ꯁꯤꯖꯁꯤꯟ ꯑꯃꯅꯤ', 'completed': 'ꯁꯛꯄꯅꯤ',
        'verified': 'ꯁꯤꯖꯁꯤꯟꯂꯤꯅꯤ', 'rejected': 'ꯆꯥꯟꯕꯅꯤ', 'approved': 'ꯁꯤꯖꯁꯤꯟꯂꯤꯅꯤ',
        'inProgress': 'ꯁꯤꯆꯥꯟꯕ ꯑꯃꯅꯤ', 'critical': 'ꯁꯤꯖꯁꯤꯟꯕ', 'high': 'ꯅꯤꯡꯊꯤ', 'medium': 'ꯁꯤꯖꯁꯤꯟ',
        'low': 'ꯈꯣꯟꯕ', 'warning': 'ꯁꯤꯖꯁꯤꯟꯕ', 'danger': 'ꯈꯣꯟꯕ',
        'primary': 'ꯁꯤꯖꯁꯤꯟꯕ', 'secondary': 'ꯁꯤꯖꯁꯤꯟꯕ', 'login': 'ꯂꯣꯒꯤꯟ',
        'logout': 'ꯂꯣꯒꯤꯑꯎꯠ', 'register': 'ꯔꯤꯖꯤꯁ꯭ꯠꯔꯤꯕ', 'email': 'ꯏꯃꯦꯜ',
        'password': 'ꯄꯥꯁꯀꯣꯗ꯭', 'name': 'ꯃꯈꯣꯜ', 'description': 'ꯁꯤꯆꯥꯟꯕ',
        'details': 'ꯁꯤꯆꯥꯟꯕ', 'type': 'ꯁꯤꯖꯁꯤꯟ', 'amount': 'ꯕꯤ', 'count': 'ꯁꯤꯖꯁꯤꯟ',
        'value': 'ꯍꯧꯔꯤꯡ', 'title': 'ꯋꯥꯠꯂꯤ', 'notes': 'ꯁꯤꯆꯥꯟꯕ', 'comment': 'ꯁꯤꯖꯁꯤꯟ',
        'comments': 'ꯁꯤꯖꯁꯤꯟꯕ', 'message': 'ꯁꯤꯖꯁꯤꯟ', 'subject': 'ꯁꯤꯖꯁꯤꯟ', 'reason': 'ꯁꯤꯖꯁꯤꯟ',
        'createdAt': 'ꯃꯤꯡꯂꯤꯕ ꯑꯃꯅꯤ', 'updatedAt': 'ꯁꯤꯆꯥꯟꯕ ꯑꯃꯅꯤ', 'lastUpdated': 'ꯃꯤꯑꯣꯔꯤꯕ ꯁꯤꯖꯁꯤꯟ',
        'ago': 'ꯁꯛꯅꯕ', 'today': 'ꯑꯦꯖꯤ', 'yesterday': 'ꯆꯥꯟ', 'thisWeek': 'ꯑꯦꯁ ꯏꯔꯥ',
        'thisMonth': 'ꯑꯦꯁ ꯃꯤꯁ', 'lastMonth': 'ꯆꯥꯟ ꯃꯤꯁ', 'lastWeek': 'ꯆꯥꯟ ꯏꯔꯥ',
        'custom': 'ꯀꯁ꯭ꯠꯝ', 'dateRange': 'ꯂꯧꯁꯤꯡ ꯔꦤꯖ',
        'startDate': 'ꯂꯧꯂꯤꯡ ꯂꯧꯁꯤꯡ', 'endDate': 'ꯁꯦꯟꯂꯤꯡ ꯂꯧꯁꯤꯡ',
        'created': 'ꯃꯤꯡꯂꯤꯕ', 'updated': 'ꯁꯤꯆꯥꯟꯕ', 'deleted': 'ꯁꯤꯖꯔꯤꯕ',
        'by': 'ꯗ꯭ꯔꯥ', 'and': 'ꯑꯃꯁꯨꯅꯤ', 'or': 'ꯋꯤ', 'more': 'ꯅꯤꯡꯊꯤ', 'less': 'ꯈꯣꯟꯕ',
        'open': 'ꯁꯦꯟꯂꯤꯕ', 'export': 'ꯑꯦꯛꯁ꯭ꯄꯣꯔꯠ', 'import': 'ꯏꯝꯄꯣꯔꯠ', 'print': 'ꯄ꯭ꯔꯤꯟꯠ',
        'copy': 'ꯀꯣꯞꯤ', 'copied': 'ꯀꯣꯞꯤ ꯑꯃꯅꯤ!', 'share': 'ꯁꯦꯌꯔ ꯂꯤꯕ',
        'compare': 'ꯇꯨꯝꯕ', 'difference': 'ꯐꯔꯛ', 'summary': 'ꯁꯥꯔꯁꯝ',
        'overview': 'ꯑꯣꯚꯔ꯭ꯂꯤꯡ', 'statistics': 'ꯁ꯭ꯠꯦꯠꯁꯤꯛ', 'analytics': 'ꯐꯤꯞ꯭ꯔꯤꯁ꯭',
        'report': 'ꯔꯤꯄꯣꯔꯠ', 'reports': 'ꯔꯤꯄꯣꯔꯠꯁꯤꯡ', 'document': 'ꯗꯣꯀꯨꯝꯕ',
        'documents': 'ꯗꯣꯀꯨꯝꯕꯁꯤꯡ', 'file': 'ꯐꯥꯏꯜ', 'files': 'ꯐꯥꯏꯜꯁꯤꯡ',
        'attachment': 'ꯑꯇꯥꯛ', 'version': 'ꯚꯔꯁꯟ', 'history': 'ꯏꯔꯥꯛ',
        'timeline': 'ꯇꯥꯏꯝꯂꯤꯡ', 'recent': 'ꯑꯣꯚ꯭ꯔꯥ', 'top': 'ꯍꯧꯔꯤꯡ',
        'newest': 'ꯅꯥꯈꯜ', 'best': 'ꯁꯤꯖꯁꯤꯟꯕ', 'worst': 'ꯁꯤꯖꯁꯤꯟꯕ',
        'savedSuccessfully': 'ꯁꯛꯄꯅꯤꯗ꯭ ꯁꯦꯝꯕ ꯑꯃꯅꯤ',
        'deletedSuccessfully': 'ꯁꯛꯄꯅꯤꯗ꯭ ꯁꯤꯖꯔꯤꯕ ꯑꯃꯅꯤ',
        'updatedSuccessfully': 'ꯁꯛꯄꯅꯤꯗ꯭ ꯁꯤꯆꯥꯟꯕ ꯑꯃꯅꯤ',
        'createdSuccessfully': 'ꯁꯛꯄꯅꯤꯗ꯭ ꯃꯤꯡꯂꯤꯕ ꯑꯃꯅꯤ',
        'operationFailed': 'ꯁꯤꯆꯥꯟꯕ ꯌꯦꯡꯕ',
        'confirmDelete': 'ꯆꯥꯟꯕ ꯑꯣꯏꯔꯤꯅꯤ?',
        'cannotBeUndone': 'ꯑꯃꯁꯤ ꯂꯝꯕ ꯑꯣꯏꯔꯤꯕ ꯑꯃꯅꯤ.',
    },
}
write_locale('mni', mni_data)
print('Done: mni.json')

# ── Bodo (brx) ───────────────────────────────────────────────────────────────
brx_data = {
    'common': {
        'appName': 'वोजास', 'tagline': 'एम.पी.एल.ए.डी. जवाबदेही प्लेटफार्म',
        'loading': 'लोडिंग...', 'error': 'गोथो', 'success': 'सफल',
        'save': 'हानसाव', 'cancel': 'रद्द कराव', 'delete': 'हेराव', 'edit': 'सुधाराव',
        'create': 'बनाव', 'search': 'खोजाव', 'filter': 'फिल्टर', 'clear': 'साफ कराव',
        'apply': 'लागू कराव', 'back': 'गोलाव', 'next': 'फिनाव', 'previous': 'सोलाव',
        'submit': 'जमा कराव', 'reset': 'रीसेट', 'confirm': 'सुनिश्चित कराव',
        'close': 'बंद कराव', 'view': 'देखाव', 'download': 'डाउनलोड',
        'upload': 'अपलोड', 'refresh': 'रिफ्रेश', 'retry': 'फिर कोशिश',
        'noData': 'कोनो डेटा नै', 'notFound': 'नै मिले',
        'unauthorized': 'अनधिकृत', 'forbidden': 'प्रवेश निषेध',
        'serverError': 'सर्वर गोथो', 'networkError': 'नेटवर्क गोथो',
        'unknownError': 'अज्ञात गोथो', 'pageNotFound': 'पेज नै मिले',
        'goHome': 'डैशबोर्डार जा', 'language': 'फोरम', 'selectLanguage': 'फोरम बयल कराव',
        'changeLanguage': 'फोरम सोलाव', 'allLanguages': 'सब फोरम',
        'perPage': 'प्रति पेज', 'date': 'तारीख', 'status': 'हालत', 'actions': 'कार्रवाई',
        'viewAll': 'सब देखाव', 'required': 'जरूरी', 'optional': 'वैकल्पिक',
        'yes': 'हां', 'no': 'नै', 'all': 'सब', 'select': 'बयल कराव',
        'selectOption': 'एक विकल्प बयल कराव', 'noResults': 'कोनो नतीजा नै',
        'processing': 'प्रोसेसिंग...', 'pending': 'विचाराधीन',
        'active': 'सक्रिय', 'inactive': 'निष्क्रिय', 'completed': 'पूर्ण',
        'verified': 'सत्यापित', 'rejected': 'नकारल', 'approved': 'मंजूर',
        'inProgress': 'जारी', 'critical': 'गंभीर', 'high': 'उच्च', 'medium': 'मध्यम',
        'low': 'निम्न', 'warning': 'चेतावनी', 'danger': 'खतरा',
        'primary': 'मुख्य', 'secondary': 'द्वितीयक', 'login': 'लॉगिन',
        'logout': 'लॉगआउट', 'register': 'पंजीकरण', 'email': 'ईमेल',
        'password': 'पासवर्ड', 'name': 'नां', 'description': 'विवरण',
        'details': 'विस्तृत', 'type': 'प्रकार', 'amount': 'राशि', 'count': 'गणना',
        'value': 'मूल्य', 'title': 'शीर्षक', 'notes': 'नोट्स', 'comment': 'टिप्पणी',
        'comments': 'टिप्पणीया', 'message': 'संदेश', 'subject': 'विषय', 'reason': 'कारण',
        'createdAt': 'बनाया', 'updatedAt': 'अपडेट', 'lastUpdated': 'आखरी अपडेट',
        'ago': 'पहलें', 'today': 'आज', 'yesterday': 'काल', 'thisWeek': 'ई हप्ते',
        'thisMonth': 'ई महिने', 'lastMonth': 'पिछला महिना', 'lastWeek': 'पिछला हप्ता',
        'custom': 'कस्टम', 'dateRange': 'तारीख रेंज',
        'startDate': 'सुरुआत तारीख', 'endDate': 'अंत तारीख',
        'created': 'बनाया', 'updated': 'अपडेट', 'deleted': 'हेराया',
        'by': 'द्वारा', 'and': 'और', 'or': 'या', 'more': 'और', 'less': 'कम',
        'open': 'खोलाव', 'export': 'निर्यात', 'import': 'आयात', 'print': 'छापाव',
        'copy': 'कॉपी', 'copied': 'कॉपी जाया!', 'share': 'शेयर कराव',
        'compare': 'तुलना', 'difference': 'अंतर', 'summary': 'सारांश',
        'overview': 'अवलोकन', 'statistics': 'आंकड़े', 'analytics': 'विश्लेषण',
        'report': 'रिपोर्ट', 'reports': 'रिपोर्टां', 'document': 'दस्तावेज',
        'documents': 'दस्तावेजां', 'file': 'फाइल', 'files': 'फाइलां',
        'attachment': 'संलग्न', 'version': 'संस्करण', 'history': 'इतिहास',
        'timeline': 'टाइमलाइन', 'recent': 'हालिया', 'top': 'शीर्ष',
        'newest': 'नवीन', 'best': 'बेस्ट', 'worst': 'वर्स्ट',
        'savedSuccessfully': 'सफलतापूर्वक हानसाया',
        'deletedSuccessfully': 'सफलतापूर्वक हेराया',
        'updatedSuccessfully': 'सफलतापूर्वक अपडेट काया',
        'createdSuccessfully': 'सफलतापूर्वक बनाया',
        'operationFailed': 'कार्रवाई असफल',
        'confirmDelete': 'के तूं सच्चमुख हेराना चाहदा है?',
        'cannotBeUndone': 'ई कार्रवाई वापस नै करि सकिन.',
    },
}
write_locale('brx', brx_data)
print('Done: brx.json')

# ── Santhali / Ol Chiki (sat) ───────────────────────────────────────────────
sat_data = {
    'common': {
        'appName': 'ᱚᱡᱟᱥ', 'tagline': 'ᱮᱞ.ᱯᱤ.ᱮᱞ.ᱮ.ᱰᱤ. ᱠᱚᱨᱚᱲᱤᱭᱟᱹᱛᱤ ᱯᱞᱮᱴᱯᱷᱚᱨᱢ',
        'loading': 'ᱞᱚᱰᱤᱝ...', 'error': 'ᱵᱷᱩᱞ', 'success': 'ᱥᱟᱠᱟᱨ',
        'save': 'ᱯᱷᱮᱢᱚᱝ', 'cancel': 'ᱵᱟᱰᱟᱭ', 'delete': 'ᱥᱮᱞᱮᱫ', 'edit': 'ᱥᱟᱯᱲᱟ',
        'create': 'ᱛᱮᱥᱟᱨ', 'search': 'ᱯᱚᱱᱰᱮ', 'filter': 'ᱯᱤᱞᱴᱚᱨ', 'clear': 'ᱥᱮᱫᱟᱭ',
        'apply': 'ᱵᱟᱪᱷᱟᱣ', 'back': 'ᱢᱟᱲᱟᱝ', 'next': 'ᱚᱛᱚᱨ', 'previous': 'ᱢᱩᱬ',
        'submit': 'ᱪᱟᱞᱟᱣ', 'reset': 'ᱨᱤᱥᱮᱴ', 'confirm': 'ᱵᱟᱰᱟᱭ',
        'close': 'ᱵᱚᱝᱜᱟ', 'view': 'ᱧᱮᱞ', 'download': 'ᱰᱟᱣᱚᱱᱞᱚᱰ',
        'upload': 'ᱚᱯᱞᱚᱰ', 'refresh': 'ᱨᱤᱯᱷᱨᱮᱥ', 'retry': 'ᱯᱚᱨᱥᱮᱨ',
        'noData': 'ᱵᱟᱝ ᱰᱟᱴᱟ ᱠᱚᱣᱟᱜ', 'notFound': 'ᱵᱟᱝ ᱧᱮᱞᱟᱭ',
        'unauthorized': 'ᱟᱝᱜᱽᱯᱚᱫ', 'forbidden': 'ᱛᱚᱞᱟᱡ ᱵᱟᱝ ᱦᱩᱭᱟᱹ',
        'serverError': 'ᱥᱟᱹᱨᱚᱵᱚᱨ ᱵᱷᱩᱞ', 'networkError': 'ᱱᱮᱛᱵᱚᱨᱠ ᱵᱷᱩᱞ',
        'unknownError': 'ᱟᱥᱚᱠᱟᱱ ᱵᱷᱩᱞ', 'pageNotFound': 'ᱯᱟᱨᱚᱢ ᱵᱟᱝ ᱧᱮᱞᱟᱭ',
        'goHome': 'ᱰᱮᱥᱵᱚᱰ ᱨᱮ ᱪᱟᱞ', 'language': 'ᱯᱟᱹᱨᱥᱤ', 'selectLanguage': 'ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ',
        'changeLanguage': 'ᱯᱟᱹᱨᱥᱤ ᱵᱟᱦᱟᱭ', 'allLanguages': 'ᱡᱚᱛᱚ ᱯᱟᱹᱨᱥᱤ',
        'perPage': 'ᱯᱟᱨᱚᱢ ᱟᱹᱜᱩᱣ', 'date': 'ᱢᱟᱱᱟᱝ', 'status': 'ᱥᱟᱛᱟᱝ', 'actions': 'ᱠᱟᱹᱞᱤᱭᱟᱹ',
        'viewAll': 'ᱡᱚᱛᱚ ᱧᱮᱞ', 'required': 'ᱵᱟᱰᱟᱭ', 'optional': 'ᱵᱟᱪᱷᱟᱣ',
        'yes': 'ᱦᱚᱸ', 'no': 'ᱵᱟᱝ', 'all': 'ᱡᱚᱛᱚ', 'select': 'ᱵᱟᱪᱷᱟᱣ',
        'selectOption': 'ᱢᱤᱫ ᱣᱟᱦᱟᱭ', 'noResults': 'ᱵᱟᱝ ᱨᱩᱯ',
        'processing': 'ᱯᱨᱚᱥᱮᱥ...', 'pending': 'ᱯᱟᱱᱰᱟᱹ',
        'active': 'ᱟᱠᱟᱱ', 'inactive': 'ᱟᱠᱟᱱᱟᱝ', 'completed': 'ᱯᱩᱨᱟᱹ',
        'verified': 'ᱯᱟᱱᱰᱟᱹ', 'rejected': 'ᱵᱟᱰᱟᱭ', 'approved': 'ᱵᱟᱰᱟᱭ',
        'inProgress': 'ᱪᱟᱞᱟᱣ', 'critical': 'ᱢᱟᱨᱟᱝ', 'high': 'ᱩᱥ', 'medium': 'ᱢᱮᱱ',
        'low': 'ᱠᱚᱢ', 'warning': 'ᱟᱝᱜᱟᱨᱤ', 'danger': 'ᱡᱚᱝᱜᱚ',
        'primary': 'ᱢᱩᱬ', 'secondary': 'ᱛᱚᱨᱡᱚ', 'login': 'ᱞᱚᱜᱤᱱ',
        'logout': 'ᱞᱚᱜᱚᱣᱴ', 'register': 'ᱨᱤᱡᱤᱥᱴᱚᱨ', 'email': 'ᱤᱢᱮᱭᱤᱞ',
        'password': 'ᱯᱟᱥᱣᱚᱰ', 'name': 'ᱧᱩᱛᱩᱢ', 'description': 'ᱛᱤᱨᱞᱟᱹ',
        'details': 'ᱛᱤᱨᱞᱟᱹᱠᱷᱟᱱᱟ', 'type': 'ᱯᱚᱱᱫᱚ', 'amount': 'ᱡᱤᱥ', 'count': 'ᱢᱟᱱᱟ',
        'value': 'ᱤᱫᱤ', 'title': 'ᱧᱩᱛᱩᱢ', 'notes': 'ᱱᱚᱴᱠ', 'comment': 'ᱢᱟᱱᱟ',
        'comments': 'ᱢᱟᱱᱟᱠᱚ', 'message': 'ᱥᱤᱫᱚ', 'subject': 'ᱵᱟᱹᱱᱩᱜ', 'reason': 'ᱠᱟᱣᱟᱜ',
        'createdAt': 'ᱛᱮᱥᱟᱨ', 'updatedAt': 'ᱚᱪᱚᱭ', 'lastUpdated': 'ᱢᱩᱬᱩᱜ ᱚᱪᱚᱭ',
        'ago': 'ᱢᱟᱲᱟᱝ', 'today': 'ᱛᱤᱥᱤ', 'yesterday': 'ᱯᱟᱨᱦᱟᱲ', 'thisWeek': 'ᱱᱟᱶᱟ',
        'thisMonth': 'ᱱᱤᱭᱟᱹ ᱪᱟᱣᱟᱱ', 'lastMonth': 'ᱯᱟᱨᱦᱟᱲ ᱪᱟᱣᱟᱱ', 'lastWeek': 'ᱯᱟᱨᱦᱟᱲ ᱱᱟᱶᱟ',
        'custom': 'ᱠᱟᱹᱴᱷᱤ', 'dateRange': 'ᱢᱟᱱᱟᱝ ᱨᱮᱤᱧ',
        'startDate': 'ᱮᱛᱚᱦᱚᱭ ᱢᱟᱱᱟᱝ', 'endDate': 'ᱢᱩᱬᱩᱜ ᱢᱟᱱᱟᱝ',
        'created': 'ᱛᱮᱥᱟᱨ', 'updated': 'ᱚᱪᱚᱭ', 'deleted': 'ᱥᱮᱞᱮᱫ',
        'by': 'ᱫᱷᱟᱹᱵᱤᱡ', 'and': 'ᱟᱨ', 'or': 'ᱵᱟᱝᱜ', 'more': 'ᱵᱤᱡᱤ', 'less': 'ᱠᱚᱢ',
        'open': 'ᱡᱟᱹᱛᱤ', 'export': 'ᱮᱠᱥᱯᱚᱨᱴ', 'import': 'ᱤᱢᱯᱚᱨᱴ', 'print': 'ᱯᱨᱤᱧᱴ',
        'copy': 'ᱠᱚᱯᱤ', 'copied': 'ᱠᱚᱯᱤ ᱜᱟᱱ!', 'share': 'ᱥᱮᱨ',
        'compare': 'ᱵᱟᱝᱠᱷᱟᱱᱟ', 'difference': 'ᱯᱩᱡᱟᱹ', 'summary': 'ᱥᱟᱨᱚᱱ',
        'overview': 'ᱥᱟᱨᱚᱱ', 'statistics': 'ᱡᱚᱛᱚ ᱛᱟᱹᱨᱤ', 'analytics': 'ᱮᱱᱟᱞᱤᱥᱤᱥ',
        'report': 'ᱨᱤᱯᱚᱨᱴ', 'reports': 'ᱨᱤᱯᱚᱨᱴᱠᱚ', 'document': 'ᱠᱟᱜᱮᱫ',
        'documents': 'ᱠᱟᱜᱮᱫᱠᱚ', 'file': 'ᱯᱟᱭᱞ', 'files': 'ᱯᱟᱭᱞᱠᱚ',
        'attachment': 'ᱞᱟᱹᱭᱱᱟᱹᱠ', 'version': 'ᱣᱚᱨᱡᱚᱱ', 'history': 'ᱨᱤᱱᱤᱡ',
        'timeline': 'ᱥᱚᱢᱚᱭ', 'recent': 'ᱱᱟᱶᱟ', 'top': 'ᱢᱩᱬ',
        'newest': 'ᱱᱟᱣᱟᱱ', 'best': 'ᱵᱷᱤᱛ', 'worst': 'ᱵᱷᱤᱛ',
        'savedSuccessfully': 'ᱥᱟᱠᱟᱨᱮ ᱯᱷᱮᱢᱚᱝ',
        'deletedSuccessfully': 'ᱥᱟᱠᱟᱨᱮ ᱥᱮᱞᱮᱫ',
        'updatedSuccessfully': 'ᱥᱟᱠᱟᱨᱮ ᱚᱪᱚᱭ',
        'createdSuccessfully': 'ᱥᱟᱠᱟᱨᱮ ᱛᱮᱥᱟᱨ',
        'operationFailed': 'ᱠᱟᱹᱞᱤᱭᱟᱹ ᱵᱷᱩᱞ',
        'confirmDelete': 'ᱟᱢᱜᱽ ᱫᱚᱦᱚᱭᱟᱧ?',
        'cannotBeUndone': 'ᱱᱚᱶᱟ ᱵᱟᱰᱟᱭ ᱵᱟᱝ ᱵᱟᱛᱚᱟ.',
    },
}
write_locale('sat', sat_data)
print('Done: sat.json')

# ── Nepali (ne) ─────────────────────────────────────────────────────────────
ne_data = {
    'common': {
        'appName': 'भोजास', 'tagline': 'एम.पी.एल.ए.डी. उत्तरदायित्व प्लेटफर्म',
        'loading': 'लोड हुँदै...', 'error': 'त्रुटि', 'success': 'सफल',
        'save': 'बचत गर्नुहोस्', 'cancel': 'रद्द गर्नुहोस्', 'delete': 'मेटाउनुहोस्', 'edit': 'सम्पादन गर्नुहोस्',
        'create': 'बनाउनुहोस्', 'search': 'खोज्नुहोस्', 'filter': 'फिल्टर', 'clear': 'खाली गर्नुहोस्',
        'apply': 'लागू गर्नुहोस्', 'back': 'पछाडि', 'next': 'अर्को', 'previous': 'अघि',
        'submit': 'पेश गर्नुहोस्', 'reset': 'रीसेट', 'confirm': 'पुष्टि गर्नुहोस्',
        'close': 'बन्द गर्नुहोस्', 'view': 'हेर्नुहोस्', 'download': 'डाउनलोड',
        'upload': 'अपलोड', 'refresh': 'रिफ्रेश', 'retry': 'पुनः प्रयास',
        'noData': 'कुनै डेटा छैन', 'notFound': 'फेला परेन',
        'unauthorized': 'अनुमति छैन', 'forbidden': 'प्रवेश निषेध',
        'serverError': 'सर्भर त्रुटि', 'networkError': 'नेटवर्क त्रुटि',
        'unknownError': 'अज्ञात त्रुटि', 'pageNotFound': 'पृष्ठ फेला परेन',
        'goHome': 'ड्यासबोर्डमा जानुहोस्', 'language': 'भाषा', 'selectLanguage': 'भाषा चयन गर्नुहोस्',
        'changeLanguage': 'भाषा परिवर्तन गर्नुहोस्', 'allLanguages': 'सबै भाषाहरू',
        'perPage': 'प्रति पृष्ठ', 'date': 'मिति', 'status': 'स्थिति', 'actions': 'कार्य',
        'viewAll': 'सबै हेर्नुहोस्', 'required': 'आवश्यक', 'optional': 'वैकल्पिक',
        'yes': 'हो', 'no': 'होइन', 'all': 'सबै', 'select': 'चयन गर्नुहोस्',
        'selectOption': 'एक विकल्प चयन गर्नुहोस्', 'noResults': 'कुनै परिणाम फेला परेन',
        'processing': 'प्रशोधन हुँदैछ...', 'pending': 'विचाराधीन',
        'active': 'सक्रिय', 'inactive': 'निष्क्रिय', 'completed': 'पूर्ण',
        'verified': 'प्रमाणित', 'rejected': 'अस्वीकृत', 'approved': 'स्वीकृत',
        'inProgress': 'जारी', 'critical': 'गम्भीर', 'high': 'उच्च', 'medium': 'मध्यम',
        'low': 'निम्न', 'warning': 'चेतावनी', 'danger': 'खतरा',
        'primary': 'प्राथमिक', 'secondary': 'माध्यमिक', 'login': 'लगइन',
        'logout': 'लगआउट', 'register': 'दर्ता', 'email': 'इमेल',
        'password': 'पासवर्ड', 'name': 'नाम', 'description': 'विवरण',
        'details': 'विवरणहरू', 'type': 'प्रकार', 'amount': 'राशि', 'count': 'गणना',
        'value': 'मूल्य', 'title': 'शीर्षक', 'notes': 'नोटहरू', 'comment': 'टिप्पणी',
        'comments': 'टिप्पणीहरू', 'message': 'सन्देश', 'subject': 'विषय', 'reason': 'कारण',
        'createdAt': 'सिर्जना गरिएको', 'updatedAt': 'अपडेट गरिएको', 'lastUpdated': 'अन्तिम अपडेट',
        'ago': 'अघि', 'today': 'आज', 'yesterday': 'हिजो', 'thisWeek': 'यस हप्ता',
        'thisMonth': 'यस महिना', 'lastMonth': 'गत महिना', 'lastWeek': 'गत हप्ता',
        'custom': 'अनुकूलन', 'dateRange': 'मिति दायरा',
        'startDate': 'सुरुवात मिति', 'endDate': 'अन्त्य मिति',
        'created': 'सिर्जना', 'updated': 'अपडेट', 'deleted': 'मेटाइएको',
        'by': 'द्वारा', 'and': 'र', 'or': 'वा', 'more': 'थप', 'less': 'कम',
        'open': 'खोल्नुहोस्', 'export': 'निर्यात', 'import': 'आयात', 'print': 'प्रिन्ट',
        'copy': 'प्रतिलिपि', 'copied': 'प्रतिलिपि भयो!', 'share': 'सेयर',
        'compare': 'तुलना', 'difference': 'भिन्नता', 'summary': 'सारांश',
        'overview': 'अवलोकन', 'statistics': 'तथ्याङ्क', 'analytics': 'विश्लेषण',
        'report': 'प्रतिवेदन', 'reports': 'प्रतिवेदनहरू', 'document': 'कागजात',
        'documents': 'कागजातहरू', 'file': 'फाइल', 'files': 'फाइलहरू',
        'attachment': 'संलग्न', 'version': 'संस्करण', 'history': 'इतिहास',
        'timeline': 'समयरेखा', 'recent': 'हालको', 'top': 'शीर्ष',
        'newest': 'नयाँ', 'best': 'उत्तम', 'worst': 'नराम्रो',
        'savedSuccessfully': 'सफलतापूर्वक बचत गरियो',
        'deletedSuccessfully': 'सफलतापूर्वक मेटाइयो',
        'updatedSuccessfully': 'सफलतापूर्वक अपडेट गरियो',
        'createdSuccessfully': 'सफलतापूर्वक सिर्जना गरियो',
        'operationFailed': 'कार्य असफल',
        'confirmDelete': 'तपाईं साँच्चै मेटाउन चाहनुहुन्छ?',
        'cannotBeUndone': 'यो कार्य पूर्ववत गर्न सकिँदैन.',
    },
}
write_locale('ne', ne_data)
print('Done: ne.json')

# ── Kashmiri / Devanagari (ks) ───────────────────────────────────────────────
ks_data = {
    'common': {
        'appName': 'वोजास', 'tagline': 'एम.पी.एल.ए.डी. जवाबदेही प्लैटफॉर्म',
        'loading': 'लोड हुनु...', 'error': 'चूक', 'success': 'कामयाब',
        'save': 'बचाव', 'cancel': 'रद्द', 'delete': 'मिटाव', 'edit': 'संपादन',
        'create': 'बनाव', 'search': 'खोजाव', 'filter': 'फिल्टर', 'clear': 'साफ कराव',
        'apply': 'लागू कराव', 'back': 'पीछे', 'next': 'अगला', 'previous': 'पिछला',
        'submit': 'जमा कराव', 'reset': 'रीसेट', 'confirm': 'पुष्टि',
        'close': 'बंद कराव', 'view': 'देखाव', 'download': 'डाउनलोड',
        'upload': 'अपलोड', 'refresh': 'रिफ्रेश', 'retry': 'फिर कोशिश',
        'noData': 'कोई डेटा नै', 'notFound': 'नै मिल्ला',
        'unauthorized': 'गैर-अधिकृत', 'forbidden': 'प्रवेश मना',
        'serverError': 'सर्वर चूक', 'networkError': 'नेटवर्क चूक',
        'unknownError': 'अज्ञात चूक', 'pageNotFound': 'पेज नै मिल्ली',
        'goHome': 'डैशबोर्ड पर जा', 'language': 'ज़बान', 'selectLanguage': 'ज़बान चुनाव',
        'changeLanguage': 'ज़बान बदलाव', 'allLanguages': 'सभ ज़बानां',
        'perPage': 'प्रति पेज', 'date': 'तारीख', 'status': 'हालत', 'actions': 'कार्रवाई',
        'viewAll': 'सभ देखाव', 'required': 'ज़रूरी', 'optional': 'वैकल्पिक',
        'yes': 'हां', 'no': 'नै', 'all': 'सभ', 'select': 'चुनाव',
        'selectOption': 'एक विकल्प चुनाव', 'noResults': 'कोई नतीजा नै',
        'processing': 'प्रोसेसिंग...', 'pending': 'विचाराधीन',
        'active': 'सक्रिय', 'inactive': 'निष्क्रिय', 'completed': 'पूर्ण',
        'verified': 'सत्यापित', 'rejected': 'नकारल', 'approved': 'मंजूर',
        'inProgress': 'जारी', 'critical': 'गंभीर', 'high': 'उच्च', 'medium': 'मध्यम',
        'low': 'निम्न', 'warning': 'चेतावनी', 'danger': 'खतरा',
        'primary': 'मुख्य', 'secondary': 'द्वितीयक', 'login': 'लॉगिन',
        'logout': 'लॉगआउट', 'register': 'रजिस्टर', 'email': 'ईमेल',
        'password': 'पासवर्ड', 'name': 'नाम', 'description': 'विवरण',
        'details': 'विस्तृत', 'type': 'प्रकार', 'amount': 'राशि', 'count': 'गणना',
        'value': 'मूल्य', 'title': 'शीर्षक', 'notes': 'नोट्स', 'comment': 'टिप्पणी',
        'comments': 'टिप्पणियां', 'message': 'संदेश', 'subject': 'विषय', 'reason': 'कारण',
        'createdAt': 'बनाया', 'updatedAt': 'अपडेट', 'lastUpdated': 'आखरी अपडेट',
        'ago': 'पहलें', 'today': 'आज', 'yesterday': 'कल', 'thisWeek': 'इस हफ्ते',
        'thisMonth': 'इस महीने', 'lastMonth': 'पिछले महीने', 'lastWeek': 'पिछले हफ्ते',
        'custom': 'कस्टम', 'dateRange': 'तारीख रेंज',
        'startDate': 'शुरुआत तारीख', 'endDate': 'अंत तारीख',
        'created': 'बनाया', 'updated': 'अपडेट', 'deleted': 'मिटाया',
        'by': 'द्वारा', 'and': 'और', 'or': 'या', 'more': 'और', 'less': 'कम',
        'open': 'खोलाव', 'export': 'निर्यात', 'import': 'आयात', 'print': 'छापाव',
        'copy': 'कॉपी', 'copied': 'कॉपी जाया!', 'share': 'शेयर कराव',
        'compare': 'तुलना', 'difference': 'अंतर', 'summary': 'सारांश',
        'overview': 'अवलोकन', 'statistics': 'आंकड़े', 'analytics': 'विश्लेषण',
        'report': 'रिपोर्ट', 'reports': 'रिपोर्टां', 'document': 'दस्तावेज',
        'documents': 'दस्तावेज', 'file': 'फाइल', 'files': 'फाइलां',
        'attachment': 'संलग्न', 'version': 'संस्करण', 'history': 'इतिहास',
        'timeline': 'टाइमलाइन', 'recent': 'हालिया', 'top': 'शीर्ष',
        'newest': 'नवीन', 'best': 'बेस्ट', 'worst': 'वर्स्ट',
        'savedSuccessfully': 'कामयाबी खाफियत बचाव',
        'deletedSuccessfully': 'कामयाबी खाफियत मिटाया',
        'updatedSuccessfully': 'कामयाबी खाफियत अपडेट',
        'createdSuccessfully': 'कामयाबी खाफियत बनाया',
        'operationFailed': 'कार्रवाई असफल',
        'confirmDelete': 'क्या तूं सच्चमुख मिटाना चाहदा है?',
        'cannotBeUndone': 'इ कार्रवाई वापस नै करि सकती.',
    },
}
write_locale('ks', ks_data)
print('Done: ks.json')
print('ALL 13 REMAINING LANGUAGES GENERATED!')
