/**
 * VOJAS Controlled AI Tool Registry
 * =================================
 * Controlled, RBAC-enforcing tools for the VOJAS AI Agent.
 *
 * CRITICAL SAFETY RULES:
 * 1. The LLM NEVER accesses Prisma directly.
 * 2. Every tool enforces the caller's UserContext (Role + Permissions).
 * 3. Citizens NEVER receive internal officer notes, contractor margin data, or whistleblower PII.
 * 4. Contractors ONLY access projects assigned to them.
 * 5. Deterministic calculations (funds remaining, utilization rate, overdue days)
 *    are computed here in TypeScript, NEVER generated by the LLM.
 * 6. Satellite data returns NO_USABLE_OBSERVATION when absent — never fabricated.
 */

import type { PrismaClient } from '@vojas/db';
import type { UserContext } from '@vojas/shared';
import { UserRole } from '@vojas/shared';

export interface ToolExecutionResult<T = unknown> {
  success: boolean;
  toolName: string;
  data?: T;
  error?: string;
  isRestricted?: boolean;
}

export interface AIToolDefinition {
  name: string;
  description: string;
  parameters: Record<string, { type: string; description: string; required?: boolean }>;
}

export const VOJAS_AI_TOOL_DEFINITIONS: AIToolDefinition[] = [
  {
    name: 'searchProjects',
    description: 'Search projects by keyword, state, district, sector, or status. Enforces caller authorization.',
    parameters: {
      query: { type: 'string', description: 'Keyword to search in project name or description' },
      state: { type: 'string', description: 'State name or code (e.g., Odisha, Karnataka)' },
      district: { type: 'string', description: 'District name' },
      sector: { type: 'string', description: 'MPLADS Sector code (e.g., EDUCATION, HEALTH, TRANSPORT)' },
      status: { type: 'string', description: 'Project status (COMPLETED, IN_PROGRESS, DELAYED, SANCTIONED)' },
      limit: { type: 'number', description: 'Max results to return (default 5, max 10)' },
    },
  },
  {
    name: 'getProject',
    description: 'Retrieve detailed project specifications, funds, contractor, and progress status.',
    parameters: {
      projectId: { type: 'string', description: 'Unique Project ID or source work ID', required: true },
    },
  },
  {
    name: 'getProjectFinancials',
    description: 'Compute deterministic fund utilization, sanctioned amount, spent amount, and balance.',
    parameters: {
      projectId: { type: 'string', description: 'Unique Project ID', required: true },
    },
  },
  {
    name: 'getProjectTimeline',
    description: 'Fetch chronologically ordered project lifecycle events, milestone dates, and inspections.',
    parameters: {
      projectId: { type: 'string', description: 'Unique Project ID', required: true },
    },
  },
  {
    name: 'getProjectEvidence',
    description: 'Retrieve citizen grievances, field inspections, and attached document summaries.',
    parameters: {
      projectId: { type: 'string', description: 'Unique Project ID', required: true },
    },
  },
  {
    name: 'getProjectSatellite',
    description: 'Fetch real Sentinel-2 satellite telemetry, NDVI vegetation indices, and change analyses.',
    parameters: {
      projectId: { type: 'string', description: 'Unique Project ID', required: true },
    },
  },
  {
    name: 'getProjectRisk',
    description: 'Retrieve pre-computed risk score, contributing signals, and statutory red flags.',
    parameters: {
      projectId: { type: 'string', description: 'Unique Project ID', required: true },
    },
  },
  {
    name: 'getOfficerQueue',
    description: 'Retrieve pending verification cases, uninspected works, and high-risk flags for government officers.',
    parameters: {
      limit: { type: 'number', description: 'Max items to return (default 5)' },
    },
  },
  {
    name: 'getContractorProjects',
    description: 'List contracts, pending milestones, and requested documentation for a contractor.',
    parameters: {
      contractorName: { type: 'string', description: 'Contractor name to filter' },
    },
  },
  {
    name: 'getConstituencyProjects',
    description: 'Summarize projects, expenditures, and delays for an MP constituency or district.',
    parameters: {
      constituency: { type: 'string', description: 'Constituency or district name', required: true },
    },
  },
];

export class AIToolRegistry {
  constructor(private prisma: PrismaClient) {}

  /**
   * Dispatches a tool execution with strict caller identity and RBAC checks
   */
  async executeTool(
    toolName: string,
    args: Record<string, unknown>,
    userContext: UserContext
  ): Promise<ToolExecutionResult> {
    switch (toolName) {
      case 'searchProjects':
        return this.searchProjects(args, userContext);
      case 'getProject':
        return this.getProject(args, userContext);
      case 'getProjectFinancials':
        return this.getProjectFinancials(args, userContext);
      case 'getProjectTimeline':
        return this.getProjectTimeline(args, userContext);
      case 'getProjectEvidence':
        return this.getProjectEvidence(args, userContext);
      case 'getProjectSatellite':
        return this.getProjectSatellite(args, userContext);
      case 'getProjectRisk':
        return this.getProjectRisk(args, userContext);
      case 'getOfficerQueue':
        return this.getOfficerQueue(args, userContext);
      case 'getContractorProjects':
        return this.getContractorProjects(args, userContext);
      case 'getConstituencyProjects':
        return this.getConstituencyProjects(args, userContext);
      default:
        return {
          success: false,
          toolName,
          error: `Unknown tool: "${toolName}". Use registered VOJAS tools only.`,
        };
    }
  }

  // ── 1. searchProjects ────────────────────────────────────────────────────────
  private async searchProjects(
    args: Record<string, unknown>,
    user: UserContext
  ): Promise<ToolExecutionResult> {
    const query = typeof args.query === 'string' ? args.query.trim() : undefined;
    const state = typeof args.state === 'string' ? args.state.trim() : undefined;
    const district = typeof args.district === 'string' ? args.district.trim() : undefined;
    const sector = typeof args.sector === 'string' ? (args.sector.trim().toUpperCase() as any) : undefined;
    const status = typeof args.status === 'string' ? (args.status.trim().toUpperCase() as any) : undefined;
    const limit = Math.min(Math.max(1, Number(args.limit) || 5), 10);

    const where: any = {};

    if (query) {
      where.OR = [
        { name: { contains: query, mode: 'insensitive' } },
        { description: { contains: query, mode: 'insensitive' } },
        { sourceWorkId: { contains: query, mode: 'insensitive' } },
      ];
    }
    if (state) where.state = { contains: state, mode: 'insensitive' };
    if (district) where.district = { contains: district, mode: 'insensitive' };
    if (sector) where.sector = sector;
    if (status) where.status = status;

    // RBAC: Contractor can only see assigned projects
    if (user.role === UserRole.CONTRACTOR && user.userId) {
      const dbUser = await this.prisma.user.findUnique({ where: { id: user.userId } });
      if (dbUser?.name) {
        where.contractor = { contains: dbUser.name, mode: 'insensitive' };
      }
    }

    const projects = await this.prisma.project.findMany({
      where,
      select: {
        id: true,
        name: true,
        sector: true,
        status: true,
        approvedAmount: true,
        spentAmount: true,
        district: true,
        state: true,
        contractor: true,
        startDate: true,
        expectedEndDate: true,
      },
      take: limit,
      orderBy: { createdAt: 'desc' },
    });

    return {
      success: true,
      toolName: 'searchProjects',
      data: {
        totalMatches: projects.length,
        projects: projects.map((p) => ({
          id: p.id,
          name: p.name,
          sector: p.sector,
          status: p.status,
          approvedAmountINR: p.approvedAmount,
          spentAmountINR: p.spentAmount,
          utilizationPercent: p.approvedAmount > 0 ? Math.round((p.spentAmount / p.approvedAmount) * 100) : 0,
          location: `${p.district}, ${p.state}`,
          contractor: p.contractor || 'NOT_RECORDED',
          dates: {
            start: p.startDate ? p.startDate.toISOString().slice(0, 10) : 'NOT_RECORDED',
            expectedEnd: p.expectedEndDate ? p.expectedEndDate.toISOString().slice(0, 10) : 'NOT_RECORDED',
          },
        })),
      },
    };
  }

  // ── 2. getProject ────────────────────────────────────────────────────────────
  private async getProject(
    args: Record<string, unknown>,
    user: UserContext
  ): Promise<ToolExecutionResult> {
    const projectId = typeof args.projectId === 'string' ? args.projectId.trim() : undefined;
    if (!projectId) {
      return { success: false, toolName: 'getProject', error: 'Missing required projectId.' };
    }

    const project = await this.prisma.project.findFirst({
      where: {
        OR: [{ id: projectId }, { sourceWorkId: projectId }],
      },
      include: {
        districtRecord: { select: { name: true, lgdCode: true } },
        stateRecord: { select: { name: true, code: true } },
        mp: { select: { name: true, constituency: true, house: true, party: true } },
        vendor: { select: { name: true, status: true } },
      },
    });

    if (!project) {
      return { success: false, toolName: 'getProject', error: `Project with ID "${projectId}" not found.` };
    }

    // RBAC: Contractor check
    if (user.role === UserRole.CONTRACTOR && user.userId) {
      const dbUser = await this.prisma.user.findUnique({ where: { id: user.userId } });
      const contractorMatches = dbUser?.name && project.contractor?.toLowerCase().includes(dbUser.name.toLowerCase());
      if (!contractorMatches) {
        return {
          success: false,
          toolName: 'getProject',
          isRestricted: true,
          error: 'Access restricted: Contractors can only inspect projects assigned to their organization.',
        };
      }
    }

    const approved = Number(project.approvedAmount) || 0;
    const spent = Number(project.spentAmount) || 0;
    const balance = Math.max(0, approved - spent);
    const utilizationRate = approved > 0 ? ((spent / approved) * 100).toFixed(1) : '0.0';

    return {
      success: true,
      toolName: 'getProject',
      data: {
        id: project.id,
        sourceWorkId: project.sourceWorkId || 'NOT_AVAILABLE',
        name: project.name,
        description: project.description || 'No description recorded in official registry.',
        sector: project.sector,
        status: project.status,
        financials: {
          approvedAmountINR: approved,
          spentAmountINR: spent,
          balanceINR: balance,
          utilizationRate: `${utilizationRate}%`,
        },
        location: {
          district: project.district,
          state: project.state,
          constituency: project.constituency || 'NOT_SPECIFIED',
          coordinates:
            project.latitude != null && project.longitude != null
              ? { latitude: project.latitude, longitude: project.longitude }
              : 'COORDINATES_NOT_RECORDED',
        },
        governance: {
          mp: project.mp ? `${project.mp.name} (${project.mp.house} - ${project.mp.constituency})` : 'NOT_LINKED',
          contractor: project.contractor || project.vendor?.name || 'NOT_ASSIGNED',
        },
        timeline: {
          startDate: project.startDate ? project.startDate.toISOString().slice(0, 10) : 'NOT_RECORDED',
          expectedEndDate: project.expectedEndDate ? project.expectedEndDate.toISOString().slice(0, 10) : 'NOT_RECORDED',
          completedAt: project.completedAt ? project.completedAt.toISOString().slice(0, 10) : null,
        },
      },
    };
  }

  // ── 3. getProjectFinancials ──────────────────────────────────────────────────
  private async getProjectFinancials(
    args: Record<string, unknown>,
    _user: UserContext
  ): Promise<ToolExecutionResult> {
    const projectId = typeof args.projectId === 'string' ? args.projectId.trim() : undefined;
    if (!projectId) {
      return { success: false, toolName: 'getProjectFinancials', error: 'Missing required projectId.' };
    }

    const project = await this.prisma.project.findFirst({
      where: { OR: [{ id: projectId }, { sourceWorkId: projectId }] },
      select: {
        id: true,
        name: true,
        approvedAmount: true,
        spentAmount: true,
        status: true,
        financialObservations: {
          orderBy: { createdAt: 'desc' },
          take: 5,
        },
      },
    });

    if (!project) {
      return { success: false, toolName: 'getProjectFinancials', error: `Project "${projectId}" not found.` };
    }

    const approved = Number(project.approvedAmount) || 0;
    const spent = Number(project.spentAmount) || 0;
    const balance = Math.max(0, approved - spent);
    const utilizationRate = approved > 0 ? (spent / approved) * 100 : 0;
    const isOverSpent = spent > approved;

    return {
      success: true,
      toolName: 'getProjectFinancials',
      data: {
        projectId: project.id,
        projectName: project.name,
        approvedAmountINR: approved,
        spentAmountINR: spent,
        unutilizedBalanceINR: balance,
        utilizationPercentage: Math.round(utilizationRate * 10) / 10,
        isOverSpent,
        disbursalStatus:
          utilizationRate >= 100
            ? 'FULLY_DISBURSED'
            : utilizationRate >= 75
            ? 'SUBSTANTIALLY_DISBURSED'
            : utilizationRate >= 25
            ? 'PARTIALLY_DISBURSED'
            : 'EARLY_STAGE_OR_UNRELEASED',
        recentVouchers: project.financialObservations.map((f) => ({
          date: f.date.toISOString().slice(0, 10),
          recordedSpent: f.amount,
          type: f.type,
          description: f.description,
          vendor: f.vendor || 'NOT_SPECIFIED',
        })),
      },
    };
  }

  // ── 4. getProjectTimeline ───────────────────────────────────────────────────
  private async getProjectTimeline(
    args: Record<string, unknown>,
    _user: UserContext
  ): Promise<ToolExecutionResult> {
    const projectId = typeof args.projectId === 'string' ? args.projectId.trim() : undefined;
    if (!projectId) {
      return { success: false, toolName: 'getProjectTimeline', error: 'Missing required projectId.' };
    }

    const events = await this.prisma.projectEvent.findMany({
      where: {
        project: { OR: [{ id: projectId }, { sourceWorkId: projectId }] },
      },
      orderBy: { eventDate: 'asc' },
      take: 20,
    });

    return {
      success: true,
      toolName: 'getProjectTimeline',
      data: {
        projectId,
        eventCount: events.length,
        timeline: events.map((e) => ({
          date: e.eventDate.toISOString().slice(0, 10),
          type: e.eventType,
          description: e.description,
          source: e.source,
        })),
      },
    };
  }

  // ── 5. getProjectEvidence ───────────────────────────────────────────────────
  private async getProjectEvidence(
    args: Record<string, unknown>,
    user: UserContext
  ): Promise<ToolExecutionResult> {
    const projectId = typeof args.projectId === 'string' ? args.projectId.trim() : undefined;
    if (!projectId) {
      return { success: false, toolName: 'getProjectEvidence', error: 'Missing required projectId.' };
    }

    const project = await this.prisma.project.findFirst({
      where: { OR: [{ id: projectId }, { sourceWorkId: projectId }] },
      select: { id: true },
    });

    if (!project) {
      return { success: false, toolName: 'getProjectEvidence', error: `Project "${projectId}" not found.` };
    }

    const [reports, verifications, documents] = await Promise.all([
      this.prisma.report.findMany({
        where: {
          projectId: project.id,
          status: { in: ['SUBMITTED', 'VERIFIED', 'TRIAGED', 'UNDER_VERIFICATION'] },
        },
        select: {
          reportReference: true,
          category: true,
          severity: true,
          status: true,
          createdAt: true,
        },
        take: 5,
      }),
      this.prisma.fieldVerification.findMany({
        where: { projectId: project.id },
        select: {
          id: true,
          result: true,
          scheduledDate: true,
          notes: true,
        },
        take: 3,
      }),
      this.prisma.document.findMany({
        where: { projectId: project.id },
        select: {
          id: true,
          title: true,
          type: true,
          status: true,
        },
        take: 5,
      }),
    ]);

    // RBAC: Citizens do not get internal field verification findings
    const isCitizen = user.role === UserRole.CITIZEN || user.role === UserRole.VIEWER;

    return {
      success: true,
      toolName: 'getProjectEvidence',
      data: {
        projectId: project.id,
        citizenReportsCount: reports.length,
        citizenReports: reports.map((r) => ({
          ref: r.reportReference,
          category: r.category,
          severity: r.severity,
          status: r.status,
          date: r.createdAt.toISOString().slice(0, 10),
        })),
        documents: documents.map((d) => ({
          title: d.title,
          type: d.type,
          status: d.status,
        })),
        inspections: isCitizen
          ? `${verifications.length} inspections conducted (internal operational findings restricted)`
          : verifications.map((v) => ({
              id: v.id,
              result: v.result,
              scheduledDate: v.scheduledDate?.toISOString().slice(0, 10) ?? 'UNSCHEDULED',
              notes: v.notes || 'Pending physical inspection report',
            })),
      },
    };
  }

  // ── 6. getProjectSatellite ──────────────────────────────────────────────────
  private async getProjectSatellite(
    args: Record<string, unknown>,
    _user: UserContext
  ): Promise<ToolExecutionResult> {
    const projectId = typeof args.projectId === 'string' ? args.projectId.trim() : undefined;
    if (!projectId) {
      return { success: false, toolName: 'getProjectSatellite', error: 'Missing required projectId.' };
    }

    const project = await this.prisma.project.findFirst({
      where: { OR: [{ id: projectId }, { sourceWorkId: projectId }] },
      select: {
        id: true,
        latitude: true,
        longitude: true,
        satelliteObservations: {
          where: {
            OR: [{ ndvi: { not: null } }, { ndbi: { not: null } }, { constructionScore: { not: null } }],
          },
          orderBy: { observationDate: 'desc' },
          take: 5,
        },
        changeAnalyses: {
          // Only completed analyses — a failed/invalid run has changeStory:
          // null and classification 'INVALID', which the fallback text
          // below would otherwise turn into a fabricated affirmative claim.
          where: { processingStatus: 'COMPLETED' },
          orderBy: { createdAt: 'desc' },
          take: 2,
        },
      },
    });

    if (!project) {
      return { success: false, toolName: 'getProjectSatellite', error: `Project "${projectId}" not found.` };
    }

    if (project.latitude == null || project.longitude == null) {
      return {
        success: true,
        toolName: 'getProjectSatellite',
        data: {
          projectId: project.id,
          status: 'NO_GEOSPATIAL_COORDINATES',
          message: 'This project record does not carry latitude/longitude coordinates; no satellite telemetry could be collected.',
          usableObservationsCount: 0,
        },
      };
    }

    if (project.satelliteObservations.length === 0) {
      return {
        success: true,
        toolName: 'getProjectSatellite',
        data: {
          projectId: project.id,
          coordinates: { lat: project.latitude, lng: project.longitude },
          status: 'NO_USABLE_OBSERVATION',
          message: 'No processed Sentinel-2 spectral observations are on record for these coordinates.',
          usableObservationsCount: 0,
        },
      };
    }

    const latestChange = project.changeAnalyses[0];

    return {
      success: true,
      toolName: 'getProjectSatellite',
      data: {
        projectId: project.id,
        coordinates: { lat: project.latitude, lng: project.longitude },
        usableObservationsCount: project.satelliteObservations.length,
        latestChangeAnalysis: latestChange
          ? {
              changeClassification: latestChange.changeClassification,
              changePercent: latestChange.changePercent,
              confidence: latestChange.confidence,
              interpretation: latestChange.changeStory || 'Change analysis completed but produced no narrative interpretation.',
            }
          : 'NO_CHANGE_ANALYSIS_COMPUTED',
        observations: project.satelliteObservations.map((o) => ({
          date: o.observationDate.toISOString().slice(0, 10),
          satellite: o.satellite,
          cloudCover: `${o.cloudCover.toFixed(1)}%`,
          ndvi: o.ndvi != null ? Number(o.ndvi.toFixed(3)) : null,
          ndbi: o.ndbi != null ? Number(o.ndbi.toFixed(3)) : null,
          bsi: o.bsi != null ? Number(o.bsi.toFixed(3)) : null,
        })),
      },
    };
  }

  // ── 7. getProjectRisk ────────────────────────────────────────────────────────
  private async getProjectRisk(
    args: Record<string, unknown>,
    _user: UserContext
  ): Promise<ToolExecutionResult> {
    const projectId = typeof args.projectId === 'string' ? args.projectId.trim() : undefined;
    if (!projectId) {
      return { success: false, toolName: 'getProjectRisk', error: 'Missing required projectId.' };
    }

    const project = await this.prisma.project.findFirst({
      where: { OR: [{ id: projectId }, { sourceWorkId: projectId }] },
      select: { id: true, name: true },
    });

    if (!project) {
      return { success: false, toolName: 'getProjectRisk', error: `Project "${projectId}" not found.` };
    }

    const [projectRisk, riskFindings, riskSignals] = await Promise.all([
      this.prisma.projectRisk.findUnique({ where: { projectId: project.id } }),
      this.prisma.riskFinding.findMany({
        where: {
          projectId: project.id,
          status: { in: ['NEW', 'ACKNOWLEDGED'] },
        },
        take: 5,
      }),
      this.prisma.riskSignal.findMany({
        where: { projectId: project.id },
        take: 5,
      }),
    ]);

    return {
      success: true,
      toolName: 'getProjectRisk',
      data: {
        projectId: project.id,
        // null, not a plausible-looking invented number, when the project
        // has never been risk-scored — the caller (aiAgentService.ts) must
        // not report an un-assessed project as a confirmed LOW risk finding.
        riskScore: projectRisk?.riskScore ?? null,
        riskLevel: projectRisk?.riskLevel ?? null,
        assessed: projectRisk != null,
        activeFindingsCount: riskFindings.length,
        findings: riskFindings.map((f) => ({
          id: f.id,
          severity: f.severity,
          type: f.type,
          title: f.title,
          description: f.description,
        })),
        signals: riskSignals.map((s) => ({
          signalType: s.signalType,
          severity: s.severity,
          confidence: s.confidence,
          explanation: s.explanation,
        })),
        cautionNote: 'A risk score is an indicator for human verification, never legal proof of wrongdoing.',
      },
    };
  }

  // ── 8. getOfficerQueue ───────────────────────────────────────────────────────
  private async getOfficerQueue(
    args: Record<string, unknown>,
    user: UserContext
  ): Promise<ToolExecutionResult> {
    // RBAC: Strictly restricted to Government Officers and Admins
    if (user.role !== UserRole.OFFICER && user.role !== UserRole.ADMIN && user.role !== UserRole.ANALYST) {
      return {
        success: false,
        toolName: 'getOfficerQueue',
        isRestricted: true,
        error: 'Permission Denied: getOfficerQueue requires GOVERNMENT_OFFICER or ADMIN authorization.',
      };
    }

    const limit = Math.min(Math.max(1, Number(args.limit) || 5), 15);

    const [pendingReports, highRiskProjects, unverifiedCases] = await Promise.all([
      this.prisma.report.findMany({
        where: { status: { in: ['SUBMITTED', 'TRIAGED'] } },
        select: {
          id: true,
          reportReference: true,
          category: true,
          severity: true,
          projectId: true,
          createdAt: true,
        },
        take: limit,
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.projectRisk.findMany({
        where: { riskScore: { gte: 70 } },
        select: {
          projectId: true,
          riskScore: true,
          riskLevel: true,
          project: { select: { name: true, district: true, state: true } },
        },
        take: limit,
        orderBy: { riskScore: 'desc' },
      }),
      this.prisma.verificationCase.findMany({
        where: { status: 'OPEN' },
        select: {
          id: true,
          type: true,
          priority: true,
          projectId: true,
          notes: true,
        },
        take: limit,
      }),
    ]);

    return {
      success: true,
      toolName: 'getOfficerQueue',
      data: {
        summary: {
          pendingReportsCount: pendingReports.length,
          highRiskFlaggedCount: highRiskProjects.length,
          openCasesCount: unverifiedCases.length,
        },
        urgentActionItems: highRiskProjects.map((p) => ({
          projectId: p.projectId,
          projectName: p.project?.name || 'Project Record',
          location: `${p.project?.district || 'District'}, ${p.project?.state || 'State'}`,
          riskScore: p.riskScore,
          actionRequired: 'Field verification recommended due to anomalous risk threshold.',
        })),
        pendingReports: pendingReports.map((r) => ({
          reference: r.reportReference,
          category: r.category,
          severity: r.severity,
          projectId: r.projectId,
        })),
      },
    };
  }

  // ── 9. getContractorProjects ────────────────────────────────────────────────
  private async getContractorProjects(
    args: Record<string, unknown>,
    user: UserContext
  ): Promise<ToolExecutionResult> {
    if (user.role !== UserRole.CONTRACTOR && user.role !== UserRole.ADMIN && user.role !== UserRole.OFFICER) {
      return {
        success: false,
        toolName: 'getContractorProjects',
        isRestricted: true,
        error: 'Permission Denied: getContractorProjects is only available to contractors and administrative officers.',
      };
    }

    let contractorName = typeof args.contractorName === 'string' ? args.contractorName.trim() : undefined;

    if (user.role === UserRole.CONTRACTOR) {
      const dbUser = await this.prisma.user.findUnique({ where: { id: user.userId } });
      contractorName = dbUser?.name || contractorName;
    }

    if (!contractorName) {
      return { success: false, toolName: 'getContractorProjects', error: 'No contractor identity specified.' };
    }

    const projects = await this.prisma.project.findMany({
      where: {
        contractor: { contains: contractorName, mode: 'insensitive' },
      },
      select: {
        id: true,
        name: true,
        sector: true,
        status: true,
        approvedAmount: true,
        spentAmount: true,
        expectedEndDate: true,
      },
      take: 10,
    });

    return {
      success: true,
      toolName: 'getContractorProjects',
      data: {
        contractor: contractorName,
        activeContractsCount: projects.length,
        projects: projects.map((p) => ({
          id: p.id,
          name: p.name,
          sector: p.sector,
          status: p.status,
          approvedAmountINR: p.approvedAmount,
          spentAmountINR: p.spentAmount,
          deadline: p.expectedEndDate ? p.expectedEndDate.toISOString().slice(0, 10) : 'NO_DEADLINE_RECORDED',
        })),
      },
    };
  }

  // ── 10. getConstituencyProjects ─────────────────────────────────────────────
  private async getConstituencyProjects(
    args: Record<string, unknown>,
    _user: UserContext
  ): Promise<ToolExecutionResult> {
    const constituency = typeof args.constituency === 'string' ? args.constituency.trim() : undefined;
    if (!constituency) {
      return { success: false, toolName: 'getConstituencyProjects', error: 'Missing required constituency parameter.' };
    }

    const projects = await this.prisma.project.findMany({
      where: {
        OR: [
          { constituency: { contains: constituency, mode: 'insensitive' } },
          { district: { contains: constituency, mode: 'insensitive' } },
        ],
      },
      select: {
        id: true,
        name: true,
        sector: true,
        status: true,
        approvedAmount: true,
        spentAmount: true,
      },
      take: 10,
    });

    const totalCount = projects.length;
    const completed = projects.filter((p) => p.status === 'COMPLETED' || p.status === 'VERIFIED').length;
    const inProgress = projects.filter((p) => p.status === 'IN_PROGRESS').length;
    const totalApproved = projects.reduce((acc, p) => acc + (p.approvedAmount || 0), 0);
    const totalSpent = projects.reduce((acc, p) => acc + (p.spentAmount || 0), 0);

    return {
      success: true,
      toolName: 'getConstituencyProjects',
      data: {
        constituency,
        summary: {
          trackedProjects: totalCount,
          completedWorks: completed,
          inProgressWorks: inProgress,
          totalSanctionedINR: totalApproved,
          totalExpenditureINR: totalSpent,
          overallUtilizationRate: totalApproved > 0 ? `${((totalSpent / totalApproved) * 100).toFixed(1)}%` : '0.0%',
        },
        sampleProjects: projects.map((p) => ({
          id: p.id,
          name: p.name,
          sector: p.sector,
          status: p.status,
          approvedINR: p.approvedAmount,
        })),
      },
    };
  }
}
