export enum UserRole {
  ADMIN = 'ADMIN',
  OFFICER = 'OFFICER',
  ANALYST = 'ANALYST',
  REVIEWER = 'REVIEWER',
  MP = 'MP',
  CONTRACTOR = 'CONTRACTOR',
  CITIZEN = 'CITIZEN',
  FIELD_OFFICER = 'FIELD_OFFICER',
  VIEWER = 'VIEWER'
}

export enum ProjectStatus {
  PROPOSED = 'PROPOSED',
  APPROVED = 'APPROVED',
  SANCTIONED = 'SANCTIONED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  VERIFIED = 'VERIFIED',
  CANCELLED = 'CANCELLED',
  UNSANCTIONED = 'UNSANCTIONED'
}

export enum ProjectSector {
  PUBLIC_INFRASTRUCTURE = 'PUBLIC_INFRASTRUCTURE',
  WATER_SANITATION = 'WATER_SANITATION',
  EDUCATION = 'EDUCATION',
  HEALTH = 'HEALTH',
  AGRICULTURE = 'AGRICULTURE',
  ENVIRONMENT = 'ENVIRONMENT',
  TRANSPORT = 'TRANSPORT',
  ENERGY = 'ENERGY',
  HOUSING = 'HOUSING',
  RURAL_DEVELOPMENT = 'RURAL_DEVELOPMENT',
  SOCIAL_WELFARE = 'SOCIAL_WELFARE',
  PUBLIC_ADMIN = 'PUBLIC_ADMIN',
  FINANCE_PROCUREMENT = 'FINANCE_PROCUREMENT',
  JUSTICE = 'JUSTICE',
  LEGISLATIVE = 'LEGISLATIVE',
  PUBLIC_SAFETY = 'PUBLIC_SAFETY'
}

export enum ProjectEventType {
  PROPOSAL = 'PROPOSAL',
  APPROVAL = 'APPROVAL',
  SANCTION = 'SANCTION',
  FUND_RELEASE = 'FUND_RELEASE',
  CONTRACTOR_ASSIGNED = 'CONTRACTOR_ASSIGNED',
  WORK_START = 'WORK_START',
  MILESTONE = 'MILESTONE',
  PROGRESS_REPORT = 'PROGRESS_REPORT',
  SATELLITE_OBSERVATION = 'SATELLITE_OBSERVATION',
  CITIZEN_REPORT = 'CITIZEN_REPORT',
  FIELD_INSPECTION = 'FIELD_INSPECTION',
  AI_ALERT = 'AI_ALERT',
  VERIFICATION = 'VERIFICATION',
  COMPLETION = 'COMPLETION',
  ABANDONMENT = 'ABANDONMENT'
}

export enum House {
  LOK_SABHA = 'LOK_SABHA',
  RAJYA_SABHA = 'RAJYA_SABHA'
}

export enum ConstituencyType {
  LOK_SABHA = 'LOK_SABHA',
  RAJYA_SABHA = 'RAJYA_SABHA',
  STATE_ASSEMBLY = 'STATE_ASSEMBLY'
}

export enum ReportCategory {
  CONSTRUCTION_QUALITY = 'CONSTRUCTION_QUALITY',
  FINANCIAL_IRREGULARITY = 'FINANCIAL_IRREGULARITY',
  DELAYED_WORK = 'DELAYED_WORK',
  ABANDONED_WORK = 'ABANDONED_WORK',
  FAKE_DOCUMENTS = 'FAKE_DOCUMENTS',
  VENDOR_MISCONDUCT = 'VENDOR_MISCONDUCT',
  LOCATION_MISMATCH = 'LOCATION_MISMATCH',
  PROGRESS_MISMATCH = 'PROGRESS_MISMATCH',
  ENVIRONMENTAL_VIOLATION = 'ENVIRONMENTAL_VIOLATION',
  SAFETY_HAZARD = 'SAFETY_HAZARD',
  OTHER = 'OTHER'
}

export enum ReportSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum ReportStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ASSIGNED = 'ASSIGNED',
  INVESTIGATING = 'INVESTIGATING',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED'
}

export enum NotificationType {
  ANOMALY_DETECTED = 'ANOMALY_DETECTED',
  ANOMALY_ACKNOWLEDGED = 'ANOMALY_ACKNOWLEDGED',
  ANOMALY_RESOLVED = 'ANOMALY_RESOLVED',
  ANOMALY_ESCALATED = 'ANOMALY_ESCALATED',
  ANOMALY_ESCALATED_TO_LAW = 'ANOMALY_ESCALATED_TO_LAW',
  REPORT_SUBMITTED = 'REPORT_SUBMITTED',
  REPORT_ASSIGNED = 'REPORT_ASSIGNED',
  RISK_THRESHOLD = 'RISK_THRESHOLD',
  PROJECT_COMPLETED = 'PROJECT_COMPLETED',
  SYSTEM_ALERT = 'SYSTEM_ALERT'
}

export enum VendorStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  BLACKLISTED = 'BLACKLISTED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION'
}

export enum AnomalyCategory {
  DUPLICATE = 'DUPLICATE',
  COST_OUTLIER = 'COST_OUTLIER',
  TIMELINE = 'TIMELINE',
  BUDGET_OVERRUN = 'BUDGET_OVERRUN',
  STALLED = 'STALLED',
  GEOGRAPHIC = 'GEOGRAPHIC',
  COMPLIANCE = 'COMPLIANCE',
  FINANCIAL = 'FINANCIAL',
  PROGRESS_DISCREPANCY = 'PROGRESS_DISCREPANCY'
}

export enum AnomalySeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum DataSourceStatus {
  ACTIVE = 'ACTIVE',
  STALE = 'STALE',
  UNAVAILABLE = 'UNAVAILABLE',
  DEPRECATED = 'DEPRECATED'
}

export enum SignalType {
  SATELLITE_CHANGE = 'SATELLITE_CHANGE',
  PROGRESS_FINANCIAL_MISMATCH = 'PROGRESS_FINANCIAL_MISMATCH',
  PROJECT_DELAY = 'PROJECT_DELAY',
  COST_ANOMALY = 'COST_ANOMALY',
  DUPLICATE_PROJECT = 'DUPLICATE_PROJECT',
  GEOGRAPHIC_INCONSISTENCY = 'GEOGRAPHIC_INCONSISTENCY',
  DOCUMENT_INCONSISTENCY = 'DOCUMENT_INCONSISTENCY',
  CITIZEN_OFFICIAL_DISCREPANCY = 'CITIZEN_OFFICIAL_DISCREPANCY',
  CONTRACTOR_PATTERN = 'CONTRACTOR_PATTERN',
  ENVIRONMENTAL_RISK = 'ENVIRONMENTAL_RISK'
}

export enum RiskFindingStatus {
  NEW = 'NEW',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFICATION_REQUIRED = 'VERIFICATION_REQUIRED',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
  ESCALATED = 'ESCALATED'
}

export enum RiskRuleStatus {
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED'
}

export enum AuditAction {
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_FAILED_LOGIN = 'AUTH_FAILED_LOGIN',
  AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_DELETED = 'PROJECT_DELETED',
  ANOMALY_DETECTED = 'ANOMALY_DETECTED',
  ANOMALY_CREATED = 'ANOMALY_CREATED',
  ANOMALY_ACKNOWLEDGED = 'ANOMALY_ACKNOWLEDGED',
  ANOMALY_RESOLVED = 'ANOMALY_RESOLVED',
  ANOMALY_ESCALATED = 'ANOMALY_ESCALATED',
  ANOMALY_DISMISSED = 'ANOMALY_DISMISSED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_VERIFIED = 'DOCUMENT_VERIFIED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  SATELLITE_ANALYSIS_RUN = 'SATELLITE_ANALYSIS_RUN',
  FINANCIAL_UPDATE = 'FINANCIAL_UPDATE',
  VERIFICATION_COMPLETED = 'VERIFICATION_COMPLETED',
  SYSTEM_CONFIG_CHANGED = 'SYSTEM_CONFIG_CHANGED',
  REPORT_SUBMITTED = 'REPORT_SUBMITTED',
  REPORT_ASSIGNED = 'REPORT_ASSIGNED',
  REPORT_RESOLVED = 'REPORT_RESOLVED',
  VENDOR_REGISTERED = 'VENDOR_REGISTERED',
  NOTIFICATION_SENT = 'NOTIFICATION_SENT',
  RISK_FINDING_DETECTED = 'RISK_FINDING_DETECTED',
  RISK_FINDING_ACKNOWLEDGED = 'RISK_FINDING_ACKNOWLEDGED',
  RISK_FINDING_RESOLVED = 'RISK_FINDING_RESOLVED',
  RISK_FINDING_DISMISSED = 'RISK_FINDING_DISMISSED',
  RISK_FINDING_ESCALATED = 'RISK_FINDING_ESCALATED',
  RISK_SIGNAL_GENERATED = 'RISK_SIGNAL_GENERATED',
  RISK_RULE_TRIGGERED = 'RISK_RULE_TRIGGERED',
  RISK_SCORE_UPDATED = 'RISK_SCORE_UPDATED'
}
